# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .credential_networking_type import CredentialNetworkingType
from .limited_credential_networking import LimitedCredentialNetworking


class CredentialNetworking(BaseModel):
    """
    environment_variable 凭证注入时的网络策略。
    """

    type: CredentialNetworkingType
    """
    网络策略类型。
    """
    limited: Optional[LimitedCredentialNetworking] = None
    """
    `limited` 策略下的白名单。
    """
