# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class CredentialAuthType(str, Enum):
    """
    凭证 auth 类型。按值决定 `CredentialAuth` 里哪些字段被使用：
    - `mcp_oauth`：`mcp_server_url` + `access_token`(w) + 可选 `expires_at` / `refresh`
    - `static_bearer`：`mcp_server_url` + `token`(w)
    - `environment_variable`：`secret_name` + `secret_value`(w) + `networking`
    """

    mcp_oauth = "mcp_oauth"
    static_bearer = "static_bearer"
    environment_variable = "environment_variable"
