# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .credential_auth_type import CredentialAuthType
from .credential_networking import CredentialNetworking
from .mcpo_auth_refresh import MCPOAuthRefresh


class CredentialAuth(BaseModel):
    """
    凭证的鉴权细节。按 `type` 决定哪些字段非空：
    - `mcp_oauth` → `mcp_server_url` + `access_token`(write-only) + 可选 `expires_at` / `refresh`
    - `static_bearer` → `mcp_server_url` + `token`(write-only)
    - `environment_variable` → `secret_name` + `secret_value`(write-only) + `networking`

    所有 secret 字段（`access_token` / `token` / `secret_value` / `refresh.refresh_token` /
    `token_endpoint_auth.client_secret`）都是 write-only：响应永不返回。
    """

    type: CredentialAuthType
    """
    凭证 auth 类型。
    """
    mcp_server_url: Optional[str] = None
    """
    MCP server URL；`mcp_oauth` / `static_bearer` 用。
    """
    access_token: Optional[str] = None
    """
    OAuth access token；`mcp_oauth` 专用（write-only）。
    """
    expires_at: Optional[str] = None
    """
    access token 过期时间（RFC 3339）；`mcp_oauth` 专用。
    """
    refresh: Optional[MCPOAuthRefresh] = None
    """
    OAuth refresh 配置；`mcp_oauth` 专用。
    """
    token: Optional[str] = None
    """
    Bearer token；`static_bearer` 专用（write-only）。
    """
    secret_name: Optional[str] = None
    """
    环境变量名；`environment_variable` 专用。
    """
    secret_value: Optional[str] = None
    """
    环境变量值；`environment_variable` 专用（write-only）。
    """
    networking: Optional[CredentialNetworking] = None
    """
    注入时的网络策略；`environment_variable` 专用。
    """
