# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from arkruntime._models import BaseModel

from .credential_auth import CredentialAuth


class Credential(BaseModel):
    """
    一条挂在 Vault 上的凭证。
    """

    id: str
    """
    Credential ID。
    """
    type: Literal["vault_credential"]
    """
    固定 `"vault_credential"`。
    """
    vault_id: str
    """
    归属的 Vault ID。
    """
    auth: CredentialAuth
    """
    鉴权细节。响应中所有 secret 字段被抹掉。
    """
    display_name: Optional[str] = None
    """
    人类可读名称。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
