# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .mcp_probe import MCPProbe
from .refresh_object import RefreshObject
from .validation_status import ValidationStatus


class CredentialValidation(BaseModel):
    """
    ValidateCredential 接口响应：对 MCP server 做一次 live probe 的结果。
    """

    type: Literal["vault_credential_validation"]
    """
    固定 `"vault_credential_validation"`。
    """
    credential_id: str
    """
    被校验的 Credential ID。
    """
    vault_id: str
    """
    归属的 Vault ID。
    """
    validated_at: str
    """
    校验时间（RFC 3339）。
    """
    status: ValidationStatus
    """
    整体校验状态。
    """
    has_refresh_token: bool
    """
    是否配置了可用的 refresh token。
    """
    mcp_probe: MCPProbe
    """
    一次 MCP live probe 的抓包结果。
    """
    refresh: RefreshObject
    """
    refresh token 兑换的抓包结果。
    """
