# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List

from arkruntime._models import BaseModel


class LimitedCredentialNetworking(BaseModel):
    """
    environment_variable 凭证的白名单出网网络配置。
    """

    allowed_hosts: List[str]
    """
    允许出网的域名列表。
    """
