# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .credential import Credential


class ListCredentialsResponse(BaseModel):
    """
    List Credentials 响应体。

    注意：wire 上字段名是 `credentials`（与 vault / session 的 `data` 不一致），
    以 stg 实际形态为准。
    """

    credentials: List[Credential]
    """
    本页 Credential 列表。
    """
    next_page: Optional[str] = None
    """
    下一页 cursor；已列尽时为空或缺省。
    """
    total: Optional[int] = None
    """
    命中总条数（可选）。
    """
