# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .refresh_http_response import RefreshHTTPResponse


class MCPProbe(BaseModel):
    """
    凭证 validate 探测中捕获的 MCP 请求 / 响应对。
    """

    http_response: RefreshHTTPResponse
    """
    探测过程中失败的那一步捕获到的 HTTP 响应。
    """
    method: str
    """
    触发的 MCP 方法名。
    """
