# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .token_endpoint_auth import TokenEndpointAuth


class MCPOAuthRefresh(BaseModel):
    """
    MCP OAuth 凭证的 refresh 配置。
    `refresh_token` 是 write-only：写入接受，响应永不返回。
    """

    client_id: Optional[str] = None
    """
    OAuth client id。
    """
    refresh_token: Optional[str] = None
    """
    OAuth refresh token（write-only）。
    """
    token_endpoint: Optional[str] = None
    """
    OAuth token endpoint URL。
    """
    token_endpoint_auth: Optional[TokenEndpointAuth] = None
    """
    token endpoint 的鉴权配置。
    """
    resource: Optional[str] = None
    """
    OAuth resource indicator（RFC 8707），可选。
    """
    scope: Optional[str] = None
    """
    空格分隔的 OAuth scope 列表，可选。
    """
