# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class RefreshHTTPResponse(BaseModel):
    """
    凭证 validate 探测过程中捕获的一次 HTTP 响应。
    """

    body: str
    """
    响应体（可能被截断）。
    """
    body_truncated: bool
    """
    响应体是否已被截断。
    """
    content_type: str
    """
    Content-Type 头。
    """
    status_code: int
    """
    HTTP 状态码。
    """
