# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class RefreshStatus(str, Enum):
    """
    ValidateCredential 接口的 refresh 结果状态。
    """

    succeeded = "succeeded"
    failed = "failed"
    connect_error = "connect_error"
    no_refresh_token = "no_refresh_token"
