# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class TokenEndpointAuthType(str, Enum):
    """
    OAuth token endpoint 客户端鉴权方式。
    """

    none = "none"
    client_secret_basic = "client_secret_basic"
    client_secret_post = "client_secret_post"
