# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .token_endpoint_auth_type import TokenEndpointAuthType


class TokenEndpointAuth(BaseModel):
    """
    OAuth token endpoint 的客户端鉴权配置。
    `client_secret` 是 write-only：写入接受，响应永不返回。
    """

    type: TokenEndpointAuthType
    """
    鉴权方式。
    """
    client_secret: Optional[str] = None
    """
    OAuth client secret（write-only）。
    """
