# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel


class UpdateVaultRequest(BaseModel):
    """
    更新 Vault 的请求体。语义：`display_name` / `metadata` 至少给一个；
    `metadata` 走 patch。
    """

    display_name: Optional[str] = None
    """
    人类可读名称。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据（patch）。
    """
