# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel

from .credential_auth import CredentialAuth


class UpdateCredentialRequest(BaseModel):
    """
    更新 Credential 的请求体。

    `auth` 仅可更新可变字段；`mcp_server_url` / `secret_name` 创建后不可改。
    `display_name` / `metadata` 为 patch 语义。
    """

    auth: Optional[CredentialAuth] = None
    """
    鉴权细节（部分可变字段）。
    """
    display_name: Optional[str] = None
    """
    人类可读名称。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据（patch）。
    """
