# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel


class BoundingBox(BaseModel):
    """
    A layer's region in the base image, ordered as
    `[left, top, right, bottom]`.
    """

    absolute: Optional[List[int]] = None
    """
    Coordinates in base-image pixels, with the origin at the top left.
    """
    normalized: Optional[List[int]] = None
    """
    Coordinates scaled to the integer range `[0, 1000]`.
    """
