# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from typing_extensions import Required, TypedDict

from .optimize_prompt_options_param import OptimizePromptOptionsParam
from .output_format import OutputFormat
from .response_format import ResponseFormat
from .sequential_image_generation_mode import SequentialImageGenerationMode
from .sequential_image_generation_options_param import (
    SequentialImageGenerationOptionsParam,
)
from .tool_param import ToolParam


class CreateImageGenerationRequestParam(TypedDict, total=False):
    model: Required[str]
    """The model identifier to use."""

    prompt: Required[str]
    """Text prompt describing the desired image."""

    image: Optional[List[str]]
    """Reference / edit images. Each entry is a URL or a `data:` URI."""

    stream: Optional[bool]
    """Stream partial images as they are generated (server-sent events)."""

    response_format: Optional[ResponseFormat]
    """How generated image bytes are returned. Defaults to `url`."""

    seed: Optional[int]
    """Random seed for reproducible generation."""

    guidance_scale: Optional[float]
    """Classifier-free guidance scale for the text prompt."""

    image_guidance_scale: Optional[float]
    """Classifier-free guidance scale for reference images (edit / R2I)."""

    size: Optional[str]
    """Output size hint (e.g. `1024x1024`, `2K`, `adaptive`)."""

    watermark: Optional[bool]
    """Embed a watermark in the generated image."""

    sequential_image_generation: Optional[SequentialImageGenerationMode]
    """Multi-image generation mode."""

    sequential_image_generation_options: Optional[SequentialImageGenerationOptionsParam]
    """Tuning for `sequential_image_generation`."""

    optimize_prompt_options: Optional[OptimizePromptOptionsParam]
    """Prompt-optimizer quality/latency options."""

    tools: Optional[List[ToolParam]]
    """Tools the model may invoke during generation."""

    output_format: Optional[OutputFormat]
    """Container/codec for the generated image bytes."""

    layer_decomposition: Optional[bool]
    """
    Decompose one reference image into a base image and independently
    composable layers. Supported models return layer metadata in `data`.
    """
