# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .optimize_prompt_options import OptimizePromptOptions
from .output_format import OutputFormat
from .response_format import ResponseFormat
from .sequential_image_generation_mode import SequentialImageGenerationMode
from .sequential_image_generation_options import SequentialImageGenerationOptions
from .tool import Tool


class CreateImageGenerationRequest(BaseModel):
    model: str
    """
    The model identifier to use.
    """
    prompt: str
    """
    Text prompt describing the desired image.
    """
    image: Optional[List[str]] = None
    """
    Reference / edit images. Each entry is a URL or a `data:` URI.
    """
    stream: Optional[bool] = None
    """
    Stream partial images as they are generated (server-sent events).
    """
    response_format: Optional[ResponseFormat] = None
    """
    How generated image bytes are returned. Defaults to `url`.
    """
    seed: Optional[int] = None
    """
    Random seed for reproducible generation.
    """
    guidance_scale: Optional[float] = None
    """
    Classifier-free guidance scale for the text prompt.
    """
    image_guidance_scale: Optional[float] = None
    """
    Classifier-free guidance scale for reference images (edit / R2I).
    """
    size: Optional[str] = None
    """
    Output size hint (e.g. `1024x1024`, `2K`, `adaptive`).
    """
    watermark: Optional[bool] = None
    """
    Embed a watermark in the generated image.
    """
    sequential_image_generation: Optional[SequentialImageGenerationMode] = None
    """
    Multi-image generation mode.
    """
    sequential_image_generation_options: Optional[SequentialImageGenerationOptions] = (
        None
    )
    """
    Tuning for `sequential_image_generation`.
    """
    optimize_prompt_options: Optional[OptimizePromptOptions] = None
    """
    Prompt-optimizer quality/latency options.
    """
    tools: Optional[List[Tool]] = None
    """
    Tools the model may invoke during generation.
    """
    output_format: Optional[OutputFormat] = None
    """
    Container/codec for the generated image bytes.
    """
    layer_decomposition: Optional[bool] = None
    """
    Decompose one reference image into a base image and independently
    composable layers. Supported models return layer metadata in `data`.
    """
