# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .image_error import ImageError
from .image_generation_stream_event_type import ImageGenerationStreamEventType
from .tool import Tool
from .usage import Usage


class ImageGenerationStreamEvent(BaseModel):
    """
    One frame of the SSE response on POST /images/generations when
    `stream=true`. Wire format:
    event: <type>
    data:  <json>

    Three event types share this single struct (same shape as the legacy
    IDL); switch on `type` to decide which optional fields are populated:

    - `image_generation.partial_succeeded` → `image_index`, `url` *or*
    `b64_json`, `size`.
    - `image_generation.partial_failed`    → `image_index`, `error`.
    - `image_generation.completed`         → `tools`, `usage`. No `image_*`.
    """

    type: ImageGenerationStreamEventType
    """
    Discriminator.
    """
    model: str
    """
    Model that produced the result.
    """
    created: int
    """
    Unix timestamp (seconds) when the event was produced.
    """
    image_index: Optional[int] = None
    """
    0-based index of the image this event refers to (partial_* only).
    """
    url: Optional[str] = None
    """
    URL of the partially-generated image (partial_succeeded, response_format=url).
    """
    b64_json: Optional[str] = None
    """
    Base64-encoded image bytes (partial_succeeded, response_format=b64_json).
    """
    size: Optional[str] = None
    """
    Resolved size of the partial image, e.g. `1024x1024`.
    """
    tools: Optional[List[Tool]] = None
    """
    Tools invoked during the stream (completed only).
    """
    usage: Optional[Usage] = None
    """
    Token / image usage (completed only).
    """
    error: Optional[ImageError] = None
    """
    Per-event failure (partial_failed; also surfaces top-level failures).
    """
