# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .image_data_item import ImageDataItem
from .image_error import ImageError
from .tool import Tool
from .usage import Usage


class ImageGenerationResponse(BaseModel):
    model: str
    """
    Model that produced the result.
    """
    created: int
    """
    Unix timestamp (seconds) when the response was produced.
    """
    data: Optional[List[ImageDataItem]] = None
    """
    Generated images. Empty when the request failed entirely.
    """
    tools: Optional[List[Tool]] = None
    """
    Tools that were invoked.
    """
    usage: Optional[Usage] = None
    """
    Token / image usage.
    """
    error: Optional[ImageError] = None
    """
    Top-level failure (set when no images could be produced).
    """
