# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .bounding_box import BoundingBox
from .image_error import ImageError


class ImageDataItem(BaseModel):
    """
    One generated image. Exactly one of `url` / `b64_json` is set, depending on the request `response_format`.
    """

    url: Optional[str] = None
    """
    URL of the generated image. Set when `response_format=url`.
    """
    b64_json: Optional[str] = None
    """
    Base64-encoded image bytes. Set when `response_format=b64_json`.
    """
    size: Optional[str] = None
    """
    Resolved output size for this image (e.g. `1024x1024`).
    """
    error: Optional[ImageError] = None
    """
    Per-image failure (set when this slot failed while others succeeded).
    """
    z_index: Optional[int] = None
    """
    Layer stacking order. The base image is `0`; layers follow bottom-up.
    """
    bounding_box: Optional[BoundingBox] = None
    """
    Layer region in the base image. Omitted for the base image.
    """
    name: Optional[str] = None
    """
    Model-generated layer label. Omitted for the base image.
    """
    description: Optional[str] = None
    """
    Model-generated semantic description. Omitted for the base image.
    """
