# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing_extensions import Required, TypedDict


from .tool_type_param import ToolTypeParam


class ToolParam(TypedDict, total=False):
    type: Required[ToolTypeParam]
    """Tool identifier. Currently only `web_search` is supported."""
