# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel

from .env_config_type import EnvConfigType
from .networking_config import NetworkingConfig
from .packages_config import PackagesConfig


class EnvConfig(BaseModel):
    """
    Environment 的运行环境配置。按 `type` 区分 cloud / self_hosted。
    """

    type: EnvConfigType
    """
    运行环境类型。
    """
    networking: Optional[NetworkingConfig] = None
    """
    容器出网策略。
    """
    packages: Optional[PackagesConfig] = None
    """
    启动时预装的依赖包。
    """
    env: Optional[Dict[str, str]] = None
    """
    容器启动时注入的环境变量。
    """
