# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from arkruntime._models import BaseModel

from .env_config import EnvConfig
from .environment_scope import EnvironmentScope


class Environment(BaseModel):
    """
    ARK Managed Agents 控制面 Environment 资源。
    """

    id: str
    """
    Environment ID。
    """
    type: Literal["environment"]
    """
    固定 `"environment"`。
    """
    name: str
    """
    人类可读名称。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    config: Optional[EnvConfig] = None
    """
    运行环境配置。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据。
    """
    scope: Optional[EnvironmentScope] = None
    """
    一期未启用；仅协议占位。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
