# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class EnvironmentScope(str, Enum):
    """
    Environment 作用域。一期未启用；仅协议占位。
    """

    organization = "organization"
    account = "account"
