# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .work_state import WorkState


class HeartbeatWorkResponse(BaseModel):
    """
    Heartbeat work 的响应体。
    """

    last_heartbeat: str
    """
    控制面接受的 heartbeat 时间，RFC 3339。
    """
    lease_extended: bool
    """
    Lease 是否被刷新。
    """
    state: WorkState
    """
    Work 生命周期状态。
    """
    ttl_seconds: int
    """
    Lease TTL 秒数。
    """
    type: Literal["work_heartbeat"]
    """
    对象类型，固定为 `work_heartbeat`。
    """
