# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .environment import Environment


class ListEnvironmentsResponse(BaseModel):
    """
    List Environments 响应体。
    """

    data: List[Environment]
    """
    本页 Environment 列表。
    """
    next_page: Optional[str] = None
    """
    下一页 cursor（opaque）。
    - 存在 → 还有更多数据，把此值作为下次请求的 `page` 参数
    - 不存在 → 已列尽
    """
