# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .networking_type import NetworkingType


class NetworkingConfig(BaseModel):
    """
    容器出网策略。
    """

    type: NetworkingType
    """
    出网策略类型。
    """
    allow_mcp_servers: Optional[bool] = None
    """
    是否允许出网到 Environment/session 关联的 MCP servers。
    """
    allow_package_managers: Optional[bool] = None
    """
    是否允许出网到常见包管理器 (pip / apt / npm 等) 的官方镜像。
    """
    allowed_hosts: Optional[List[str]] = None
    """
    显式允许的出网域名列表；`limited` 模式下与 `allow_*` 白名单叠加生效。
    未设置时仅走 `allow_*` 语义控制。
    """
