# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel


class PackagesConfig(BaseModel):
    """
    启动时预装的依赖包。版本通过包管理器自身语义指定 (e.g. pip 用
    `"pkg==1.0.0"`；不指定版本则装最新)。
    """

    type: Optional[Literal["packages"]] = None
    """
    固定 `"packages"`；标识这是 Packages 配置。
    """
    pip: Optional[List[str]] = None
    """
    pip 依赖条目列表。
    """
    apt: Optional[List[str]] = None
    """
    apt 包名列表。
    """
    npm: Optional[List[str]] = None
    """
    npm 包名列表。
    """
    cargo: Optional[List[str]] = None
    """
    cargo crate 名列表。
    """
    gem: Optional[List[str]] = None
    """
    RubyGems gem 名列表。
    """
    go: Optional[List[str]] = None
    """
    go module import 路径列表。
    """
