# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict

from typing_extensions import TypeAliasType

PollWorkEmptyResponse = TypeAliasType("PollWorkEmptyResponse", Dict[str, object])
"""
Poll 没有可领取 work 时的响应；MA `/api/v3` 返回 HTTP 200 + `{}`。
"""
