# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class TosConfig(BaseModel):
    """
    Environment 产物存储位置。设置后 outputs 文件会注册到用户指定的 TOS
    bucket/prefix；不设置则走方舟默认存储。
    """

    bucket: Optional[str] = None
    """
    TOS bucket 名称。
    """
    prefix: Optional[str] = None
    """
    TOS 前缀。
    """
