# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel

from .env_config import EnvConfig
from .environment_scope import EnvironmentScope


class UpdateEnvironmentRequest(BaseModel):
    """
    更新 Environment 的请求体。语义：
    - 省略字段 = 保留原值
    - `description` 显式空字符串或 null = 清空
    - `config` 嵌套字段按 patch 处理
    - `metadata` 走 patch
    """

    name: Optional[str] = None
    """
    人类可读名称。
    """
    config: Optional[EnvConfig] = None
    """
    运行环境配置。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据。
    """
    scope: Optional[EnvironmentScope] = None
    """
    一期未启用；仅协议占位。
    """
