# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class WorkData(BaseModel):
    """
    Work 的业务载荷。
    """

    id: str
    """
    业务对象 ID，例如 session ID。
    """
    type: str
    """
    业务载荷类型，例如 `session`。
    """
