# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class WorkState(str, Enum):
    """
    Work 生命周期状态。
    """

    queued = "queued"
    starting = "starting"
    active = "active"
    stopping = "stopping"
    stopped = "stopped"
