# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .volc_tag import VolcTag
from .work_data import WorkData
from .work_state import WorkState


class WorkItem(BaseModel):
    """
    Worker queue 中的一条 work。
    """

    id: str
    """
    Work ID。
    """
    acknowledged_at: Optional[str] = None
    """
    Work ack 时间，RFC 3339。
    """
    created_at: str
    """
    Work 创建时间，RFC 3339。
    """
    data: WorkData
    """
    业务载荷。
    """
    environment_id: str
    """
    Environment ID。
    """
    latest_heartbeat_at: Optional[str] = None
    """
    最近 heartbeat 时间，RFC 3339。
    """
    tags: Optional[List[VolcTag]] = None
    """
    Work 标签。
    """
    secret: Optional[str] = None
    """
    Work secret；仅 poll 时返回，ack / stop 响应会抹掉。
    """
    started_at: Optional[str] = None
    """
    Work 开始时间，RFC 3339。
    """
    state: WorkState
    """
    Work 生命周期状态。
    """
    stop_requested_at: Optional[str] = None
    """
    控制面请求停止的时间，RFC 3339。
    """
    stopped_at: Optional[str] = None
    """
    Work 停止时间，RFC 3339。
    """
    type: Literal["work"]
    """
    对象类型，固定为 `work`。
    """
