# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .actor_type import ActorType


class Actor(BaseModel):
    """
    操作者，结构化表示。本期 `type` 恒为 `user_actor`。
    """

    type: ActorType
    """
    Actor 类型。
    """
    user_id: str
    """
    用户 ID。
    """
