# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel


class CreateMemoryStoreRequest(BaseModel):
    """
    创建 MemoryStore 的请求体。
    """

    name: str
    """
    人类可读名称。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据。
    """
