# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class CreateMemoryRequest(BaseModel):
    """
    创建 Memory 的请求体。`path` 在同一 store 内唯一。
    """

    path: str
    """
    文件路径。
    """
    content: str
    """
    文件内容。
    """
