# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class DeleteMemoryStoreResponse(BaseModel):
    """
    Delete MemoryStore 响应体。
    """

    id: str
    """
    被删除的 MemoryStore ID。
    """
    type: Literal["memory_store_deleted"]
    """
    固定 `"memory_store_deleted"`。
    """
