# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .memory_list_item import MemoryListItem


class ListMemoriesResponse(BaseModel):
    """
    List Memories 响应体。
    """

    data: List[MemoryListItem]
    """
    本页元素列表（memory 与 memory_prefix 混排）。
    """
    next_page: Optional[str] = None
    """
    下一页 cursor；已列尽时为空或缺省。
    """
    prefixes: List[str]
    """
    命中的所有折叠前缀。
    """
