# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .actor import Actor


class Memory(BaseModel):
    """
    一条记忆（store 内一个文件）。`content` 仅 Get 单条时返回。
    """

    id: str
    """
    Memory ID。
    """
    type: Literal["memory"]
    """
    固定 `"memory"`。
    """
    memory_store_id: str
    """
    归属的 MemoryStore ID。
    """
    path: str
    """
    store 内唯一的文件路径。
    """
    content: Optional[str] = None
    """
    文件内容，仅 GetMemory 单条时返回；List/Create/Update 响应中不携带。
    """
    content_sha256: str
    """
    内容 SHA256（十六进制）。
    """
    content_size_bytes: int
    """
    内容字节数。
    """
    memory_version_id: str
    """
    内容版本 ID。
    """
    created_by: Actor
    """
    创建人。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
