# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from arkruntime._models import BaseModel

from .actor import Actor


class MemoryStore(BaseModel):
    """
    一个记忆库。
    """

    id: str
    """
    MemoryStore ID。
    """
    type: Literal["memory_store"]
    """
    固定 `"memory_store"`。
    """
    name: str
    """
    人类可读名称。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    memory_count: int
    """
    库内 memory 条数。
    """
    storage_bytes: int
    """
    库内 memory 内容占用字节数。
    """
    session_count: int
    """
    引用了本库的 session 数。
    """
    created_by: Actor
    """
    创建人。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
    metadata: Dict[str, str]
    """
    用户自定义键值对元数据。
    """
