# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .memory_list_item_type import MemoryListItemType


class MemoryListItem(BaseModel):
    """
    List 响应 `data` 的元素：
    - `type = memory` 时为文件项，填精简元信息（不含 `content`）
    - `type = memory_prefix` 时为折叠目录项，仅 `type` + `path`（`/` 结尾）
    """

    type: MemoryListItemType
    """
    元素类型。
    """
    path: str
    """
    文件路径或折叠目录路径。
    """
    id: Optional[str] = None
    """
    Memory ID；仅 `type=memory` 时返回。
    """
    memory_store_id: Optional[str] = None
    """
    归属的 MemoryStore ID；仅 `type=memory` 时返回。
    """
    content_sha256: Optional[str] = None
    """
    内容 SHA256；仅 `type=memory` 时返回。
    """
    content_size_bytes: Optional[int] = None
    """
    内容字节数；仅 `type=memory` 时返回。
    """
    memory_version_id: Optional[str] = None
    """
    内容版本 ID；仅 `type=memory` 时返回。
    """
    created_at: Optional[str] = None
    """
    RFC 3339 时间；仅 `type=memory` 时返回。
    """
    updated_at: Optional[str] = None
    """
    RFC 3339 时间；仅 `type=memory` 时返回。
    """
