# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class UpdateMemoryRequest(BaseModel):
    """
    更新 Memory 的请求体；
    `content` 与 `path` 至少给一个（重命名或改内容）。
    """

    content: Optional[str] = None
    """
    更新后的文件内容。
    """
    path: Optional[str] = None
    """
    更新后的文件路径（重命名）。
    """
