# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Literal, Optional

from arkruntime._models import BaseModel

from .model_upgrades import ModelUpgrades


class AgentWithUpgrades(BaseModel):
    """
    Session upgrade 的目标 Agent 运行配置。

    `id` 必须等于当前 Session 的 Agent ID —— upgrade 不支持换绑到另一个
    Agent，不一致返回 403 `AgentMismatch`。

    数组字段（`tools` / `mcp_servers` / `skills`）是**整组替换**语义：省略
    表示保留原值，显式传 `[]` 表示清空。两者在 wire 上必须可区分，SDK 不能
    把空数组优化成省略字段。
    """

    type: Literal["agent_with_upgrades"]
    """
    固定 `"agent_with_upgrades"`。
    """
    id: str
    """
    Agent ID；必须与当前 Session 的 Agent ID 一致。
    """
    version: Optional[int] = None
    """
    目标 Agent 版本号。

    省略或传 `0` 表示**不锁版本、沿用 Session 当前的 Agent 快照**（注意与创建
    期不同：这里不是"走最新版"）。传正整数则以该版本的 payload 为基线物化
    ——`system` / `tools` / `mcp_servers` / `skills` / `multiagent` / `model`
    整组跟着版本走，本次请求里的同名字段再叠加其上；版本不存在返回 404。
    传负数返回 400。
    """
    model: Optional[ModelUpgrades] = None
    """
    模型运行参数升级。
    """
    system: Optional[str] = None
    """
    System prompt。
    """
    tools: Optional[List[Dict[str, object]]] = None
    """
    工具配置（整组替换）。
    """
    mcp_servers: Optional[List[Dict[str, object]]] = None
    """
    MCP server 配置（整组替换）。
    """
    skills: Optional[List[Dict[str, object]]] = None
    """
    Skill 配置（整组替换）。
    """
    multiagent: Optional[Dict[str, object]] = None
    """
    多 Agent 配置。
    """
    display_name: Optional[str] = None
    """
    Agent 展示名。
    """
