# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from typing_extensions import TypeAliasType

from .agent_ref import AgentRef

AgentIdentifier = TypeAliasType("AgentIdentifier", Union[str, AgentRef])
"""
Agent 标识：字符串 (agent_id) 或 AgentRef 对象。
由 TypeSpec union → OpenAPI `oneOf` → ogen sum type。
"""
