# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class AgentRef(BaseModel):
    """
    Agent 引用（对象形态）：`type: "agent"` + id + optional version。
    与 CreateSessionRequest.agent 联合使用。
    """

    type: Literal["agent"]
    """
    固定 `"agent"`。
    """
    id: str
    """
    Agent ID。
    """
    version: Optional[int] = None
    """
    Agent 版本号；不传走最新。
    """
