# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class Base64DocumentSource(BaseModel):
    """
    直接以 base64 携带的文档数据。
    """

    data: str
    """
    base64 文档数据。
    """
    media_type: str
    """
    MIME 类型，如 `application/pdf`。
    """
    type: Literal["base64"]
