# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class Base64ImageSource(BaseModel):
    """
    直接以 base64 携带的图片数据。
    """

    data: str
    """
    base64 图片数据。
    """
    media_type: str
    """
    MIME 类型，如 `image/png` / `image/jpeg`。
    """
    type: Literal["base64"]
