# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class CacheCreation(BaseModel):
    """
    token-usage 子段：每种缓存口径的输入 token 数。
    """

    ephemeral_1h_input_tokens: Optional[int] = None
    """
    ephemeral 1h TTL 缓存创建输入 token。
    """
    ephemeral_5m_input_tokens: Optional[int] = None
    """
    ephemeral 5m TTL 缓存创建输入 token。
    """
