# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .agent_with_upgrades import AgentWithUpgrades
from .environment_with_upgrades import EnvironmentWithUpgrades
from .managed_agents_event_params import ManagedAgentsEventParams


class CreateSessionUpgradeRequest(BaseModel):
    """
    发起一次已有 Session 的运行配置升级。

    `agent` / `environment` / `vault_ids` 至少提供一个作为升级目标，全部省略
    返回 400 `MissingUpgradeTarget`（只传 `initial_events` 不算升级目标）。
    Session 必须处于 `idle` 且上一轮 turn 以 `end_turn` 收尾，否则返回 403
    `SessionNotIdle` / `SessionNotEndTurn`；同一 Session 上一次升级尚未收敛时
    返回 403 `UpgradeInProgress`。
    """

    agent: Optional[AgentWithUpgrades] = None
    """
    目标 Agent 运行配置。
    """
    environment: Optional[EnvironmentWithUpgrades] = None
    """
    目标 Environment 运行配置。
    """
    vault_ids: Optional[List[str]] = None
    """
    Session 绑定的 Vault 列表。

    只能用来**刷新已绑定 Vault 的内容**，不能改变绑定集合：传入集合必须与
    当前 Session 的 `vault_ids` 相等（忽略顺序与重复），否则返回 403
    `VaultMismatch`。显式传 `[]` 表示声明空集，仅当当前 Session 本身没有
    Vault 绑定时通过 —— 因此省略与 `[]` 在 wire 上必须可区分，SDK 不能把
    空数组优化成省略字段。
    """
    initial_events: Optional[List[ManagedAgentsEventParams]] = None
    """
    配置切换收敛后由服务端补投的事件。当前只接受**恰好一个** `user.message`
    事件，且 content 为单个 text block、内容是 `/compact` 命令 XML；不满足
    返回 400 `InvalidInitialEvents` / `InvalidCompactCommand`。省略或传 `[]`
    表示本次不投递事件。
    """
