# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class CreateSessionResourceRequest(BaseModel):
    """
    挂载新的 SessionResource。

    当前 CreateSessionResource 端点仅接受 `type=file` 的写入路径
    （对齐 ark-agent-console 当前实现）。
    """

    type: Literal["file"]
    """
    资源类型；当前仅 `file`。
    """
    file_id: str
    """
    已注册到 file-server 的 file_id。
    """
