# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .agent_identifier import AgentIdentifier
from .environment_with_overrides import EnvironmentWithOverrides
from .session_resource import SessionResource
from .tag import Tag


class CreateSessionRequest(BaseModel):
    """
    创建会话请求。

    `agent` 字段承载两种 wire 形态：
    - 裸 `agent_id` 字符串
    - AgentRef 对象：`{"type":"agent","id":"agent_...","version":1}`
    """

    agent: AgentIdentifier
    """
    Agent 标识。
    """
    environment_id: Optional[str] = None
    """
    关联的 Environment ID。与 `environment` 二选一。
    """
    environment: Optional[EnvironmentWithOverrides] = None
    """
    关联 Environment 的覆写引用。与 `environment_id` 二选一。
    """
    tags: Optional[List[Tag]] = None
    """
    资源标签。
    """
    resources: Optional[List[SessionResource]] = None
    """
    挂载资源列表。
    """
    title: Optional[str] = None
    """
    会话人类可读标题。
    """
    vault_ids: Optional[List[str]] = None
    """
    会话可访问的 Vault ID 列表。
    """
