# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class DeleteSessionResponse(BaseModel):
    """
    Delete Session 响应体。
    """

    id: str
    """
    被删除的 Session ID。
    """
    type: str
    """
    对象类型标识。
    """
