# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .base64_document_source import Base64DocumentSource
from .file_document_source import FileDocumentSource
from .plain_text_document_source import PlainTextDocumentSource
from .url_document_source import UrlDocumentSource

DocumentSource = TypeAliasType(
    "DocumentSource",
    Annotated[
        Union[
            Base64DocumentSource,
            PlainTextDocumentSource,
            UrlDocumentSource,
            FileDocumentSource,
        ],
        Field(discriminator="type"),
    ],
)
"""
文档来源 tagged union：`base64` / `text` / `url` / `file`。
用于 ManagedAgentsDocumentBlock.source。
"""
