# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .environment_config_override import EnvironmentConfigOverride


class EnvironmentWithOverrides(BaseModel):
    """
    CreateSession 时的 Environment 覆写引用。
    """

    type: Literal["environment_with_overrides"]
    """
    固定 `"environment_with_overrides"`。
    """
    id: str
    """
    Base Environment ID。
    """
    config: Optional[EnvironmentConfigOverride] = None
    """
    运行时配置覆写。
    """
