# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel


class EnvironmentPackagesConfig(BaseModel):
    """
    Environment 覆写时使用的预装依赖包配置。
    """

    type: Optional[Literal["packages"]] = None
    """
    固定 `"packages"`。
    """
    pip: Optional[List[str]] = None
    """
    pip 依赖。
    """
    apt: Optional[List[str]] = None
    """
    apt 依赖。
    """
    npm: Optional[List[str]] = None
    """
    npm 依赖。
    """
    cargo: Optional[List[str]] = None
    """
    cargo 依赖。
    """
    gem: Optional[List[str]] = None
    """
    gem 依赖。
    """
    go: Optional[List[str]] = None
    """
    go module 依赖。
    """
