# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .environment_config_override import EnvironmentConfigOverride


class EnvironmentWithUpgrades(BaseModel):
    """
    Session upgrade 的目标 Environment 运行配置。

    `id` 必须等于当前 Session 的 Environment ID —— upgrade 不支持换绑到另一个
    Environment，不一致返回 403 `EnvironmentMismatch`；`config.type` 也必须与
    当前 Session 的环境类型一致（不支持 cloud ↔ self_hosted 互切），不一致
    返回 403 `EnvironmentTypeMismatch`。

    cloud 环境开放 `networking` / `packages` / `env` / `setup_script` 升级，
    在当前 Sandbox 上原地生效，不更换 Sandbox 实例。self_hosted 沙箱由用户
    自建，除 `config.type` 外不接受任何运行时字段（这类 Session 仍可升级
    agent 并投递 `initial_events`）；`tos` 一律拒绝，返回 400
    `TosUpgradeNotSupported`。
    """

    type: Literal["environment_with_upgrades"]
    """
    固定 `"environment_with_upgrades"`。
    """
    id: str
    """
    Environment ID；必须与当前 Session 的 Environment ID 一致。
    """
    config: Optional[EnvironmentConfigOverride] = None
    """
    运行时配置升级。
    """
