# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel

from .environment_networking_config import EnvironmentNetworkingConfig
from .environment_packages_config import EnvironmentPackagesConfig
from .environment_tos_config import EnvironmentTosConfig


class EnvironmentConfigOverride(BaseModel):
    """
    Environment 覆写时使用的运行环境配置。
    """

    type: str
    """
    运行环境类型。
    """
    networking: Optional[EnvironmentNetworkingConfig] = None
    """
    容器出网策略。
    """
    packages: Optional[EnvironmentPackagesConfig] = None
    """
    启动时预装的依赖包。
    """
    env: Optional[Dict[str, str]] = None
    """
    容器环境变量。
    """
    setup_script: Optional[str] = None
    """
    沙箱启动脚本。
    """
    tos: Optional[EnvironmentTosConfig] = None
    """
    Environment outputs 的 TOS 存储配置。
    """
