# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel


class EnvironmentNetworkingConfig(BaseModel):
    """
    Environment 覆写时使用的容器出网策略。
    """

    type: str
    """
    出网策略类型。
    """
    allow_mcp_servers: Optional[bool] = None
    """
    是否允许出网到 MCP servers。
    """
    allow_package_managers: Optional[bool] = None
    """
    是否允许访问包管理器。
    """
    allowed_hosts: Optional[List[str]] = None
    """
    显式允许的出网域名。
    """
