# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class FileDocumentSource(BaseModel):
    """
    通过 Files API 上传后引用的文档。
    """

    file_id: str
    """
    file id，形如 `file_...`。
    """
    type: Literal["file"]
