# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .base64_image_source import Base64ImageSource
from .file_image_source import FileImageSource
from .url_image_source import UrlImageSource

ImageSource = TypeAliasType(
    "ImageSource",
    Annotated[
        Union[Base64ImageSource, UrlImageSource, FileImageSource],
        Field(discriminator="type"),
    ],
)
"""
图片来源 tagged union：`base64` / `url` / `file`。
用于 ManagedAgentsImageBlock.source。
"""
