# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List

from arkruntime._models import BaseModel

from .session_resource import SessionResource


class ListSessionResourcesResponse(BaseModel):
    """
    List SessionResources 响应体。
    """

    data: List[SessionResource]
    """
    已挂载的 SessionResource 列表。
    """
