# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from arkruntime._models import BaseModel


class ListSessionEventsResponseWire(BaseModel):
    """
    ListSessionEvents wire response. The `data` field carries the raw
    SessionEvent union (30+ variants: agent.* / session.* / span.* /
    user.* echoes); the Go SDK dispatches each item into a concrete
    ManagedAgentsSessionEvent typed variant on the client side. This
    model is the internal wire shape — SDKs expose a friendlier struct
    with a typed Events slice.
    """

    data: List[Dict[str, object]]
    """
    本页事件（原始 wire JSON）。
    """
    next_page: Optional[str] = None
    """
    下一页 cursor；已列尽时为空或缺省。
    """
