# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .session import Session


class ListSessionsResponse(BaseModel):
    """
    List Sessions 响应体。
    """

    data: List[Session]
    """
    本页 Session 列表。
    """
    next_page: Optional[str] = None
    """
    下一页 cursor；已列尽时为空或缺省。
    """
