# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class ManagedAgentsTextBlock(BaseModel):
    """
    文本块。用于 user.message / tool_result / system.message 的 content 列表。
    """

    text: str
    """
    文本内容。
    """
    type: Literal["text"]
