# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .managed_agents_delta_text_block import ManagedAgentsDeltaTextBlock


class ManagedAgentsDeltaContent(BaseModel):
    """
    `event_delta.delta` 的 `content_delta` 载荷。`content` 是一个文本片段，
    `index` 指定它落到最终事件 `content[]` 的位置。
    """

    type: Literal["content_delta"]
    """
    固定 `"content_delta"`，区别于 Messages API 的 `content_block_delta`。
    """
    content: ManagedAgentsDeltaTextBlock
    """
    与最终 `agent.message.content[]` / `agent.thinking.content[]` 元素同形的文本片段。
    """
    index: Optional[int] = None
    """
    最终 `content[]` 的下标。新 index 插入条目，已见过的 index 追加文本。
    当前 agent-loop 总会写出该字段；公开层保留 optional 以兼容历史帧。
    """
