# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .managed_agents_agent_message_preview import ManagedAgentsAgentMessagePreview
from .managed_agents_agent_thinking_preview import ManagedAgentsAgentThinkingPreview

ManagedAgentsStartEventPreview = TypeAliasType(
    "ManagedAgentsStartEventPreview",
    Annotated[
        Union[ManagedAgentsAgentMessagePreview, ManagedAgentsAgentThinkingPreview],
        Field(discriminator="type"),
    ],
)
"""
`event_start.event` 的 tagged union。目标事件的 `type` 决定后续
`event_delta` 应累积到 `agent.message` 还是 `agent.thinking`。
"""
