# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .managed_agents_delta_event import ManagedAgentsDeltaEvent
from .managed_agents_start_event import ManagedAgentsStartEvent

ManagedAgentsStreamPreviewEvent = TypeAliasType(
    "ManagedAgentsStreamPreviewEvent",
    Annotated[
        Union[ManagedAgentsStartEvent, ManagedAgentsDeltaEvent],
        Field(discriminator="type"),
    ],
)
"""
流式预览新增的两种 SSE 帧。
"""
