# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .managed_agents_delta_content import ManagedAgentsDeltaContent


class ManagedAgentsDeltaEvent(BaseModel):
    """
    `event_delta`：仍在流式生成的事件增量。客户端用 `event_id` 反查前面的
    `event_start.event.type`，并按 `(event_id, index)` 累积文本。该帧是
    best-effort 预览，不进入事件历史，也不携带顶层 `id` / `processed_at`。
    """

    type: Literal["event_delta"]
    """
    固定 `"event_delta"`。
    """
    delta: ManagedAgentsDeltaContent
    """
    被预览事件的一个内容增量。
    """
    event_id: str
    """
    对应 `event_start.event.id`，也与最终完整 buffered 事件的 id 一致。
    """
