# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class ManagedAgentsSessionEvent(BaseModel):
    """
    会话流上的一个事件。`type` 是判别式，其余字段随 type 变化。SDK 层建议
    把这个模型作为出流事件的公共 envelope；具体 variant 的 payload 可以在
    消费侧按 `type` 再解构。
    """

    type: str
    """
    事件类型判别式，例如 `agent.message` / `span.outcome_evaluation_end` / `session.status_idle`。
    """
    id: Optional[str] = None
    """
    事件 id（服务端在 ingest 阶段 stamp，形如 `sevt-<ts>-<rand>`）。
    """
    processed_at: Optional[str] = None
    """
    事件产生时间（RFC 3339）。
    """
