# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .image_source import ImageSource


class ManagedAgentsImageBlock(BaseModel):
    """
    图片块。
    """

    source: ImageSource
    """
    图片来源。
    """
    type: Literal["image"]
