# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .managed_agents_message_content_block import ManagedAgentsMessageContentBlock


class ManagedAgentsUserMessageEventParams(BaseModel):
    """
    `user.message`：发一条用户输入到 agent。`content` 是多模态 block 列表。

    关于 `content` optional 语义：CMA / utoipa 把 `content` 标 required，但 wire
    层实际 sonic.Unmarshal 后 nil slice 与显式 `[]` 等价，服务端把两者都视作
    "no-op user.message"（旧客户端的 keepalive/ping 调用依赖它）。因此这里
    declare 成 optional，让 SDK 可以 marshal 出不带 `content` 字段的 wire body。
    """

    content: Optional[List[ManagedAgentsMessageContentBlock]] = None
    """
    消息 content：多模态 block 列表（text / image / document）。
    """
    session_id: Optional[str] = None
    """
    目标 session id；SDK 通常从 URL 路径推断，此字段可省。
    """
    type: Literal["user.message"]
