# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class ManagedAgentsDeltaTextBlock(BaseModel):
    """
    `content_delta.content` 的文本片段。wire 形态与 buffered 事件中的 text block
    相同；单独建模可在直接引用时保留必需的 `type: "text"` discriminator。
    """

    type: Literal["text"]
    """
    固定 `"text"`。
    """
    text: str
    """
    本帧新增的文本。
    """
