# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .managed_agents_text_block import ManagedAgentsTextBlock

ManagedAgentsSystemContentBlock = TypeAliasType(
    "ManagedAgentsSystemContentBlock",
    Annotated[ManagedAgentsTextBlock, Field(discriminator="type")],
)
"""
`system.message` 的 content 列表元素——目前仅支持文本块，保留 union 语义以便
未来无破坏性扩展（image / document 等）。
"""
