# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ManagedAgentsUserInterruptEventParams(BaseModel):
    """
    `user.interrupt`：打断当前进行中的 turn。
    """

    reason: Optional[str] = None
    """
    打断原因（可选）。
    """
    session_id: Optional[str] = None
    """
    目标 session id；SDK 通常从 URL 路径推断。
    """
    session_thread_id: Optional[str] = None
    """
    目标 session_thread_id（可选）。
    """
    type: Literal["user.interrupt"]
