# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .managed_agents_rubric import ManagedAgentsRubric


class ManagedAgentsUserDefineOutcomeEventParams(BaseModel):
    """
    `user.define_outcome`：声明本 session 的目标 / 评估 rubric，runtime 终局
    跑评测时使用。`max_iterations` 范围 1..=20，缺省由 server 解析为 3。
    """

    description: str
    """
    目标描述。
    """
    outcome_id: Optional[str] = None
    """
    outcome id（客户端自定义 unique key）；缺省时由服务端在事件入库前 stamp
    一个 `outc-<ts>-<rand>` 形态的 id 出来（见 ark-agent-event
    eventservice.go::ensureUserEventID 的 envelope-level mint 逻辑），
    因此 wire 上此字段是 optional，不是 required。
    """
    rubric: ManagedAgentsRubric
    """
    评测 rubric。
    """
    max_iterations: Optional[int] = None
    """
    最大迭代次数，1–20；缺省 server 解析为 3。
    """
    session_id: Optional[str] = None
    """
    目标 session id。
    """
    type: Literal["user.define_outcome"]
