# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .managed_agents_start_event_preview import ManagedAgentsStartEventPreview


class ManagedAgentsStartEvent(BaseModel):
    """
    `event_start`：打开一次 buffered 事件的流式预览。该帧仅在流式接口通过
    `event_deltas` opt-in 后出现，不进入事件历史，也不携带顶层 `id` /
    `processed_at`。通常由相同 id 的完整 buffered 事件收尾；若模型请求中途
    结束，则由对应的 `span.model_request_end` 关闭预览。
    """

    type: Literal["event_start"]
    """
    固定 `"event_start"`。
    """
    event: ManagedAgentsStartEventPreview
    """
    被预览的 `agent.message` 或 `agent.thinking`。
    """
