# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class ManagedAgentsAgentThinkingPreview(BaseModel):
    """
    `agent.thinking` 的流式预览标识。`id` 同时关联后续 `event_delta.event_id`
    与最终完整 `agent.thinking.id`。
    """

    id: str
    """
    被预览事件的 id。
    """
    type: Literal["agent.thinking"]
    """
    固定 `"agent.thinking"`。
    """
