# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .tool_confirmation_result import ToolConfirmationResult


class ManagedAgentsUserToolConfirmationEventParams(BaseModel):
    """
    `user.tool_confirmation`：响应 agent 发起的 tool 调用授权请求；
    runtime 收到后放行 / 拒绝当前 tool_use。
    """

    result: ToolConfirmationResult
    """
    授权结果。
    """
    tool_use_id: str
    """
    关联的 tool_use_id。
    """
    deny_message: Optional[str] = None
    """
    `deny` 时的说明信息。
    """
    session_id: Optional[str] = None
    """
    目标 session id。
    """
    session_thread_id: Optional[str] = None
    """
    目标 session_thread_id。
    """
    turn_id: Optional[str] = None
    """
    关联的 turn id。
    """
    type: Literal["user.tool_confirmation"]
