# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .managed_agents_system_content_block import ManagedAgentsSystemContentBlock


class ManagedAgentsSystemMessageEventParams(BaseModel):
    """
    `system.message`：把 system 侧的显式消息插入到 turn 输入（用于 rubric
    补充、外部 world state 灌注等场景）。`content` 是文本 block 列表。
    """

    content: Optional[List[ManagedAgentsSystemContentBlock]] = None
    """
    消息 content：目前仅支持文本块。
    """
    session_id: Optional[str] = None
    """
    目标 session id；SDK 通常从 URL 路径推断，此字段可省。
    """
    session_thread_id: Optional[str] = None
    """
    目标 session_thread_id（可选）。
    """
    type: Literal["system.message"]
