# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .managed_agents_file_rubric_params import ManagedAgentsFileRubricParams
from .managed_agents_text_rubric_params import ManagedAgentsTextRubricParams

ManagedAgentsRubric = TypeAliasType(
    "ManagedAgentsRubric",
    Annotated[
        Union[ManagedAgentsFileRubricParams, ManagedAgentsTextRubricParams],
        Field(discriminator="type"),
    ],
)
"""
评测 rubric tagged union——`file` 引用 / 内联 `text`。
"""
