# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .document_source import DocumentSource


class ManagedAgentsDocumentBlock(BaseModel):
    """
    文档块。
    """

    source: DocumentSource
    """
    文档来源。
    """
    title: Optional[str] = None
    """
    文档标题。
    """
    context: Optional[str] = None
    """
    上下文说明。
    """
    type: Literal["document"]
