# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .managed_agents_system_message_event_params import (
    ManagedAgentsSystemMessageEventParams,
)
from .managed_agents_user_custom_tool_result_event_params import (
    ManagedAgentsUserCustomToolResultEventParams,
)
from .managed_agents_user_define_outcome_event_params import (
    ManagedAgentsUserDefineOutcomeEventParams,
)
from .managed_agents_user_interrupt_event_params import (
    ManagedAgentsUserInterruptEventParams,
)
from .managed_agents_user_message_event_params import (
    ManagedAgentsUserMessageEventParams,
)
from .managed_agents_user_tool_confirmation_event_params import (
    ManagedAgentsUserToolConfirmationEventParams,
)
from .managed_agents_user_tool_result_event_params import (
    ManagedAgentsUserToolResultEventParams,
)

ManagedAgentsEventParams = TypeAliasType(
    "ManagedAgentsEventParams",
    Annotated[
        Union[
            ManagedAgentsUserMessageEventParams,
            ManagedAgentsSystemMessageEventParams,
            ManagedAgentsUserInterruptEventParams,
            ManagedAgentsUserToolConfirmationEventParams,
            ManagedAgentsUserToolResultEventParams,
            ManagedAgentsUserCustomToolResultEventParams,
            ManagedAgentsUserDefineOutcomeEventParams,
        ],
        Field(discriminator="type"),
    ],
)
"""
客户端可提交的 7 种事件 tagged union（discriminator = `type`）。
SDK marshal 变体时自动注入 `"type": "<value>"`，调用方不必手填该字段。

变体名的 `.` 通过反引号 escape，但 discriminator 值就是原始形态
（如 `"user.message"`）。
"""
