# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .managed_agents_document_block import ManagedAgentsDocumentBlock
from .managed_agents_image_block import ManagedAgentsImageBlock
from .managed_agents_text_block import ManagedAgentsTextBlock

ManagedAgentsMessageContentBlock = TypeAliasType(
    "ManagedAgentsMessageContentBlock",
    Annotated[
        Union[
            ManagedAgentsTextBlock, ManagedAgentsImageBlock, ManagedAgentsDocumentBlock
        ],
        Field(discriminator="type"),
    ],
)
"""
`user.message` 的 content 列表元素 tagged union（discriminator = `type`）。
支持 3 种模态：`text` / `image` / `document`。
"""
