# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class ModelOverrides(BaseModel):
    """
    Session 创建时允许临时覆写的模型运行参数。
    """

    speed: Optional[str] = None
    """
    模型速度档位。
    """
    thinking: Optional[str] = None
    """
    thinking 配置。
    """
    reasoning_effort: Optional[str] = None
    """
    推理努力程度。
    """
