# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class ModelUpgrades(BaseModel):
    """
    Session upgrade 中允许调整的模型配置子集。

    与创建期的 `ModelOverrides` 的差别在于 `id`：upgrade 允许改模型身份，
    服务端把它解析成完整 provider / protocol / endpoint 后冻结进 Session 的
    Agent 快照。
    """

    id: Optional[str] = None
    """
    目标模型标识，形如 `"doubao-seed-2-0-pro-260215"`。

    与创建期 `ModelOverrides.id` 的**解析路径不同**：此处服务端拿它当
    endpoint 反查元数据来得到 (name, version)，而不是按字符串拆分。因此
    endpoint 不存在 / 已关闭 / 元信息缺失均返回 400；显式传空串也返回 400
    （upgrade 不支持卸载底模）。模型未开通返回 403 `ModelNotOpen`；底模不支持
    作为 Agent 使用返回 400。

    换 `id` 时 `speed` / `thinking` / `reasoning_effort` / `service_tier` 会按
    **新**底模重新校验取值：本次未显式提供的，沿用升级前的值参与校验，落在新
    底模白名单外返回 400。
    """
    speed: Optional[str] = None
    """
    模型速度档位。
    """
    thinking: Optional[str] = None
    """
    thinking 配置。
    """
    reasoning_effort: Optional[str] = None
    """
    推理努力程度。
    """
    service_tier: Optional[str] = None
    """
    服务档位。
    """
