# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class PlainTextDocumentSource(BaseModel):
    """
    纯文本文档；`media_type` 必须为 `text/plain`；`data` 是原文。
    """

    data: str
    """
    文档原文。
    """
    media_type: str
    """
    MIME 类型，固定 `text/plain`。
    """
    type: Literal["text"]
