# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List

from arkruntime._models import BaseModel


class SendSessionEventsResponse(BaseModel):
    """
    SendSessionEvents 响应体（回执）。
    """

    data: List[Dict[str, object]]
    """
    服务端落库 / 转发完成后的事件回声。
    """
