# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List

from arkruntime._models import BaseModel

from .managed_agents_event_params import ManagedAgentsEventParams


class SendSessionEventsRequest(BaseModel):
    """
    SendSessionEvents 请求体。
    """

    events: List[ManagedAgentsEventParams]
    """
    事件列表；按 `type` 路由到具体事件类型。
    """
