# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class SendSessionEventsResponse(BaseModel):
    """
    SendSessionEvents 响应体（回执）。
    """

    success: Optional[bool] = None
    """
    是否成功接收（server 决定语义）。
    """
