# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class SessionResourceAccess(str, Enum):
    """
    MemoryStore 挂载访问权限。
    """

    read_only = "read_only"
    read_write = "read_write"
