# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .session_resource_access import SessionResourceAccess
from .session_resource_type import SessionResourceType


class SessionResource(BaseModel):
    """
    会话挂载的资源。按 `type` 决定字段：
    - `file` → `file_id`
    - `memory_store` → `memory_store_id` + `access`
    - `tos` → `tos_bucket` + `tos_key` + 可选 `tos_region`

    `mount_path` 描述在 sandbox 中的挂载点，各类型都可用。
    """

    id: Optional[str] = None
    """
    SessionResource ID。
    """
    type: SessionResourceType
    """
    资源类型。
    """
    file_id: Optional[str] = None
    """
    `file` 类型：已注册的文件 ID。
    """
    memory_store_id: Optional[str] = None
    """
    `memory_store` 类型：挂载的 MemoryStore ID。
    """
    access: Optional[SessionResourceAccess] = None
    """
    `memory_store` 类型：访问权限。
    """
    mount_path: Optional[str] = None
    """
    在 sandbox 中的挂载路径。
    """
    created_at: Optional[str] = None
    """
    RFC 3339 时间。
    """
    updated_at: Optional[str] = None
    """
    RFC 3339 时间。
    """
    tos_bucket: Optional[str] = None
    """
    `tos` 类型：TOS bucket。
    """
    tos_key: Optional[str] = None
    """
    `tos` 类型：TOS 对象 key。
    """
    tos_region: Optional[str] = None
    """
    `tos` 类型：TOS 区域，可选。
    """
