# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .cache_creation import CacheCreation


class SessionUsage(BaseModel):
    """
    会话 token / 缓存用量。
    """

    input_tokens: int
    """
    累计输入 token。
    """
    output_tokens: int
    """
    累计输出 token。
    """
    cache_read_input_tokens: int
    """
    累计从缓存读取的输入 token。
    """
    cache_creation: Optional[CacheCreation] = None
    """
    缓存创建 token 明细。
    """
