# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .session_thread_status import SessionThreadStatus


class SessionThread(BaseModel):
    """
    Session 内一个 thread（primary 或子 agent 生成的 thread）。

    视图由 service 层从 events collection 派生（见
    ark-managed-agents/app/ark-agent-event/biz/service/event/thread_service.go），
    不持独立 schema。
    """

    id: str
    """
    thread id。
    """
    session_id: str
    """
    所属 session id。
    """
    type: Literal["session_thread"]
    """
    固定 `"session_thread"`。
    """
    status: SessionThreadStatus
    """
    thread 运行时状态。
    """
    agent_name: str
    """
    thread 关联的 agent 名。
    """
    parent_thread_id: Optional[str] = None
    """
    primary thread 时返回 `null`；子 thread 指向父 thread id。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
