# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Literal, Optional

from arkruntime._models import BaseModel

from .session_resource import SessionResource
from .session_status import SessionStatus
from .session_usage import SessionUsage
from .tag import Tag


class Session(BaseModel):
    """
    一次 Agent 会话。

    `agent` 字段是创建时刻的 Agent 快照（同 `Ark.Agent` 命名空间下 Agent 的
    wire shape）。为保持本模块自足，此处用 `Record<unknown>` 承载；SDK 侧
    需要强类型时可自行反序列化到 agent 包的 `Agent`。
    """

    id: str
    """
    Session ID。
    """
    type: Literal["session"]
    """
    固定 `"session"`。
    """
    status: SessionStatus
    """
    会话运行状态。
    """
    environment_id: str
    """
    关联的 Environment ID。
    """
    agent: Dict[str, object]
    """
    Agent 快照。反映创建瞬间的 Agent wire 形态；shape 与 Ark.Agent 的
    Agent 一致。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
    archived_at: Optional[str] = None
    """
    归档时间（RFC 3339）；未归档时缺省。
    """
    title: Optional[str] = None
    """
    会话人类可读标题。
    """
    resources: Optional[List[SessionResource]] = None
    """
    挂载资源列表。
    """
    vault_ids: Optional[List[str]] = None
    """
    会话可访问的 Vault ID 列表。
    """
    usage: Optional[SessionUsage] = None
    """
    累计 token / 缓存用量。
    """
    tags: Optional[List[Tag]] = None
    """
    资源标签。
    """
