# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class SessionThreadStatus(str, Enum):
    """
    SessionThread 运行时状态。视图从 events collection 派生。
    """

    idle = "idle"
    running = "running"
    terminated = "terminated"
    archived = "archived"
