# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .tag import Tag


class UpdateSessionRequest(BaseModel):
    """
    局部更新会话；所有字段均 optional，omit 表示保留。
    """

    tags: Optional[List[Tag]] = None
    """
    资源标签（整体替换）。
    """
    title: Optional[str] = None
    """
    会话人类可读标题。
    """
