# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import Required, TypedDict

from .embedding_input_type import EmbeddingInputType
from .image_url_param import ImageURLParam
from .video_url_param import VideoURLParam


class EmbeddingInputParam(TypedDict, total=False):
    type: Required[EmbeddingInputType]
    """Discriminator for which content field is set."""

    text: Optional[str]
    """Text content. Required when `type` is `text`."""

    image_url: Optional[ImageURLParam]
    """Image content. Required when `type` is `image_url`."""

    video_url: Optional[VideoURLParam]
    """Video content. Required when `type` is `video_url`."""
