# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .embedding_input_type import EmbeddingInputType
from .image_url import ImageURL
from .video_url import VideoURL


class EmbeddingInput(BaseModel):
    type: EmbeddingInputType
    """
    Discriminator for which content field is set.
    """
    text: Optional[str] = None
    """
    Text content. Required when `type` is `text`.
    """
    image_url: Optional[ImageURL] = None
    """
    Image content. Required when `type` is `image_url`.
    """
    video_url: Optional[VideoURL] = None
    """
    Video content. Required when `type` is `video_url`.
    """
