# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .prompt_tokens_details import PromptTokensDetails


class EmbeddingUsage(BaseModel):
    prompt_tokens: int
    """
    The number of prompt tokens used.
    """
    total_tokens: int
    """
    The total number of tokens used.
    """
    prompt_tokens_details: PromptTokensDetails
    """
    A detailed breakdown of the prompt tokens.
    """
