# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .embedding import Embedding
from .sparse_embedding_value import SparseEmbeddingValue


class EmbeddingDataItem(BaseModel):
    embedding: Embedding
    """
    The (dense) embedding vector.
    """
    sparse_embedding: Optional[List[SparseEmbeddingValue]] = None
    """
    Sparse embedding entries when sparse embeddings were requested.
    """
    object: Literal["embedding"]
    """
    The object type. Always `embedding`.
    """
    multi_embedding: Optional[List[Embedding]] = None
    """
    Per-modality embeddings when `multi_embedding` was requested.
    """
