# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .embedding_data_item import EmbeddingDataItem
from .embedding_usage import EmbeddingUsage


class MultiModalEmbeddingResponse(BaseModel):
    id: str
    """
    The unique identifier for the embedding response.
    """
    model: str
    """
    The model that produced the embeddings.
    """
    created: int
    """
    Unix timestamp (in seconds) of when the response was created.
    """
    object: Literal["list"]
    """
    The object type. Always `list`.
    """
    data: EmbeddingDataItem
    """
    The embedding result.
    """
    usage: EmbeddingUsage
    """
    Token usage information.
    """
