# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing_extensions import Required, TypedDict


from .multi_embedding_mode import MultiEmbeddingMode


class MultiEmbeddingConfigParam(TypedDict, total=False):
    type: Required[MultiEmbeddingMode]
    """Whether per-modality embeddings should be returned in addition to the joint embedding."""
