# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .embedding_input import EmbeddingInput
from .encoding_format import EncodingFormat
from .multi_embedding_config import MultiEmbeddingConfig
from .sparse_embedding_config import SparseEmbeddingConfig


class MultiModalEmbeddingRequest(BaseModel):
    model: str
    """
    The model identifier to use.
    """
    input: List[EmbeddingInput]
    """
    The list of multimodal inputs to embed.
    """
    encoding_format: Optional[EncodingFormat] = None
    """
    The format embeddings are returned in. Defaults to `float`.
    """
    dimensions: Optional[int] = None
    """
    Override the embedding dimensionality.
    """
    sparse_embedding: Optional[SparseEmbeddingConfig] = None
    """
    Sparse embedding configuration.
    """
    multi_embedding: Optional[MultiEmbeddingConfig] = None
    """
    Multi-embedding configuration (per-modality vectors).
    """
    instructions: Optional[str] = None
    """
    Optional natural-language instructions to steer the embedding.
    """
