# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .multi_embedding_mode import MultiEmbeddingMode


class MultiEmbeddingConfig(BaseModel):
    type: MultiEmbeddingMode
    """
    Whether per-modality embeddings should be returned in addition to the joint embedding.
    """
