# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class PromptTokensDetails(BaseModel):
    text_tokens: int
    """
    The number of prompt tokens consumed by text inputs.
    """
    image_tokens: int
    """
    The number of prompt tokens consumed by image inputs.
    """
