# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class VideoURL(BaseModel):
    url: str
    """
    The URL of the video to embed.
    """
    fps: Optional[float] = None
    """
    Frames-per-second sampling rate for the video.
    """
