# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import TypeAlias, Union

from .chat_completion_request_assistant_message_param import (
    ChatCompletionRequestAssistantMessageParam,
)
from .chat_completion_request_system_message_param import (
    ChatCompletionRequestSystemMessageParam,
)
from .chat_completion_request_tool_message_param import (
    ChatCompletionRequestToolMessageParam,
)
from .chat_completion_request_user_message_param import (
    ChatCompletionRequestUserMessageParam,
)

ChatCompletionRequestMessageParam: TypeAlias = Union[
    ChatCompletionRequestUserMessageParam,
    ChatCompletionRequestSystemMessageParam,
    ChatCompletionRequestAssistantMessageParam,
    ChatCompletionRequestToolMessageParam,
]
