# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .chat_completion_stream_choice_logprobs import ChatCompletionStreamChoiceLogprobs
from .chat_completion_stream_response_delta import ChatCompletionStreamResponseDelta
from .finish_reason import FinishReason
from .moderation_hit_type import ModerationHitType


class ChatCompletionStreamResponseChoice(BaseModel):
    index: int
    delta: ChatCompletionStreamResponseDelta
    finish_reason: Optional[FinishReason] = None
    """
    The reason the model stopped generating tokens.
    """
    moderation_hit_type: Optional[ModerationHitType] = None
    logprobs: Optional[ChatCompletionStreamChoiceLogprobs] = None
