# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .chat_completion_message_tool_call_function import (
    ChatCompletionMessageToolCallFunction,
)
from .tool_type import ToolType


class ChatCompletionMessageToolCall(BaseModel):
    id: str
    """
    The ID of the tool call.
    """
    type: ToolType
    """
    The type of the tool. Currently, only `function` is supported.
    """
    function: ChatCompletionMessageToolCallFunction
    """
    The function that the model called.
    """
