# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .chat_completion_service_status import ChatCompletionServiceStatus
from .chat_completion_stream_response_choice import ChatCompletionStreamResponseChoice
from .completion_usage import CompletionUsage
from .response_service_tier import ResponseServiceTier


class ChatCompletionStreamResponse(BaseModel):
    id: str
    model: str
    created: int
    object: Literal["chat.completion.chunk"]
    """
    The object type. Always `chat.completion.chunk`.
    """
    choices: List[ChatCompletionStreamResponseChoice]
    usage: Optional[CompletionUsage]
    """
    Usage statistics. Only present on the final chunk (or every chunk
    when `stream_options.chunk_include_usage` is set); otherwise `null`.
    """
    service_tier: Optional[ResponseServiceTier] = None
    service_status: Optional[ChatCompletionServiceStatus] = None
