# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .chat_completion_content_part_audio import ChatCompletionContentPartAudio
from .chat_completion_content_part_file import ChatCompletionContentPartFile
from .chat_completion_content_part_image import ChatCompletionContentPartImage
from .chat_completion_content_part_text import ChatCompletionContentPartText
from .chat_completion_content_part_video import ChatCompletionContentPartVideo

ChatCompletionContentPart = TypeAliasType(
    "ChatCompletionContentPart",
    Annotated[
        Union[
            ChatCompletionContentPartText,
            ChatCompletionContentPartImage,
            ChatCompletionContentPartVideo,
            ChatCompletionContentPartAudio,
            ChatCompletionContentPartFile,
        ],
        Field(discriminator="type"),
    ],
)
