# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import Required, TypedDict


class ChatCompletionRequestMessageToolCallFunctionParam(TypedDict, total=False):
    name: Required[str]
    """The name of the function to call."""

    arguments: Optional[str]
    """
    The JSON-encoded function arguments. When omitted, the backend uses
    an empty string.
    """
