# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .chat_completion_message_content_param import ChatCompletionMessageContentParam


class ChatCompletionRequestDeveloperMessageParam(TypedDict, total=False):
    """
    Developer instructions are treated as system messages.
    """

    role: Required[Literal["developer"]]
    """The role of the message author. Always `developer`."""

    content: Required[ChatCompletionMessageContentParam]
    """The contents of the developer message."""

    name: Optional[str]
