# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .video_image_pixel_limit import VideoImagePixelLimit


class ChatCompletionContentPartVideoVideoUrl(BaseModel):
    url: Optional[str] = None
    """
    Either a URL of the video or the base64 encoded video data.
    """
    fps: Optional[float] = None
    """
    Frames-per-second sampling rate for the video.
    """
    detail: Optional[str] = None
    """
    Specifies the detail level of frames extracted from the video.
    """
    image_pixel_limit: Optional[VideoImagePixelLimit] = None
    """
    Optional pixel-size limits applied to extracted frames.
    """
    file_id: Optional[str] = None
    """
    The blob id of the video, when uploaded out-of-band.
    """
