# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict


class ChatCompletionStreamOptionsParam(TypedDict, total=False):
    include_usage: Optional[bool]
    """Whether to include token usage info in the final stream chunk."""

    chunk_include_usage: Optional[bool]
    """Whether to include token usage info in every stream chunk."""
