# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .chat_completion_token_logprob_top_logprob import (
    ChatCompletionTokenLogprobTopLogprob,
)


class ChatCompletionTokenLogprob(BaseModel):
    token: str
    logprob: float
    bytes: Optional[List[int]]
    """
    A list of integers representing the UTF-8 bytes representation of
    the token. May be `null` if there is no bytes representation.
    """
    top_logprobs: List[ChatCompletionTokenLogprobTopLogprob]
