# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .chat_completion_message_tool_call_chunk_function import (
    ChatCompletionMessageToolCallChunkFunction,
)


class ChatCompletionMessageToolCallChunk(BaseModel):
    index: int
    """
    Index of the tool call in the array of tool calls.
    """
    id: Optional[str] = None
    """
    The ID of the tool call.
    """
    type: Optional[str] = None
    """
    The type of the tool.
    """
    function: Optional[ChatCompletionMessageToolCallChunkFunction] = None
