# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import TypeAlias, Union

from .chat_completion_content_part_audio_param import (
    ChatCompletionContentPartAudioParam,
)
from .chat_completion_content_part_file_param import ChatCompletionContentPartFileParam
from .chat_completion_content_part_image_param import (
    ChatCompletionContentPartImageParam,
)
from .chat_completion_content_part_text_param import ChatCompletionContentPartTextParam
from .chat_completion_content_part_video_param import (
    ChatCompletionContentPartVideoParam,
)

ChatCompletionContentPartParam: TypeAlias = Union[
    ChatCompletionContentPartTextParam,
    ChatCompletionContentPartImageParam,
    ChatCompletionContentPartVideoParam,
    ChatCompletionContentPartAudioParam,
    ChatCompletionContentPartFileParam,
]
