# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .chat_completion_choice_logprobs import ChatCompletionChoiceLogprobs
from .chat_completion_response_message import ChatCompletionResponseMessage
from .finish_reason import FinishReason
from .moderation_hit_type import ModerationHitType


class ChatCompletionResponseChoice(BaseModel):
    index: int
    """
    The index of the choice in the list of choices.
    """
    message: ChatCompletionResponseMessage
    finish_reason: FinishReason
    """
    The reason the model stopped generating tokens.
    """
    moderation_hit_type: Optional[ModerationHitType] = None
    """
    When set, the type of moderation that was triggered.
    """
    logprobs: Optional[ChatCompletionChoiceLogprobs]
    """
    Log probability information for the choice.
    """
