# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict

from .chat_completion_response_format_json_schema_param import (
    ChatCompletionResponseFormatJsonSchemaParam,
)
from .response_format_type import ResponseFormatType


class ChatCompletionResponseFormatParam(TypedDict, total=False):
    type: Optional[ResponseFormatType]
    """The type of the response format."""

    json_schema: Optional[ChatCompletionResponseFormatJsonSchemaParam]
    """
    Structured Outputs configuration; required when `type` is
    `json_schema`.
    """
