# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, TypeAlias, Union

from .chat_completion_content_part_param import ChatCompletionContentPartParam

ChatCompletionMessageContentParam: TypeAlias = Union[
    str, List[ChatCompletionContentPartParam]
]
