# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing_extensions import Required, TypedDict


class ChatCompletionMessageToolCallFunctionParam(TypedDict, total=False):
    name: Required[str]
    """The name of the function to call."""

    arguments: Required[str]
    """
    The arguments to call the function with, as generated by the model in
    JSON format. Note that the model does not always generate valid JSON,
    and may hallucinate parameters not defined by your function schema.
    Validate the arguments in your code before calling your function.
    """
