# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .chat_completion_content_part_image_image_url import (
    ChatCompletionContentPartImageImageUrl,
)


class ChatCompletionContentPartImage(BaseModel):
    type: Literal["image_url"]
    """
    The type of the content part. Always `image_url`.
    """
    image_url: ChatCompletionContentPartImageImageUrl
