# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from typing_extensions import Required, TypedDict


class ChatCompletionResponseFormatJsonSchemaParam(TypedDict, total=False):
    name: Required[str]
    """The name of the response format."""

    description: Optional[str]
    """A description of what the response format is for."""

    schema: Optional[Dict[str, object]]
    """
    The schema for the response format, described as a JSON Schema
    object.
    """

    strict: Optional[bool]
    """
    Whether to enable strict schema adherence when generating the
    output.
    """
