# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .chat_completion_request_message_tool_call_function import (
    ChatCompletionRequestMessageToolCallFunction,
)
from .tool_type import ToolType


class ChatCompletionRequestMessageToolCall(BaseModel):
    id: Optional[str] = None
    """
    The ID of the tool call. Missing or null IDs are normalized to an
    empty string.
    """
    type: ToolType
    """
    The type of the tool. Currently, only `function` is supported.
    """
    function: ChatCompletionRequestMessageToolCallFunction
    """
    The function called in a previous assistant message.
    """
