# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .chat_completion_response_choice import ChatCompletionResponseChoice
from .chat_completion_service_status import ChatCompletionServiceStatus
from .completion_usage import CompletionUsage
from .response_service_tier import ResponseServiceTier


class ChatCompletionResponse(BaseModel):
    id: str
    """
    A unique identifier for the chat completion.
    """
    model: str
    """
    The model used for the chat completion.
    """
    created: int
    """
    The Unix timestamp (in seconds) of when the chat completion was
    created.
    """
    object: Literal["chat.completion"]
    """
    The object type. Always `chat.completion`.
    """
    choices: List[ChatCompletionResponseChoice]
    """
    A list of chat completion choices.
    """
    usage: Optional[CompletionUsage] = None
    """
    Usage statistics for the completion request.
    """
    service_tier: Optional[ResponseServiceTier] = None
    """
    The service tier used to process the request.
    """
    service_status: Optional[ChatCompletionServiceStatus] = None
    """
    Service status information attached to the response.
    """
