# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .chat_completion_message_content import ChatCompletionMessageContent
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall


class ChatCompletionRequestAssistantMessage(BaseModel):
    role: Literal["assistant"]
    """
    The role of the messages author. Always `assistant`.
    """
    content: Optional[ChatCompletionMessageContent] = None
    """
    The contents of the assistant message. Required unless `tool_calls`
    is specified.
    """
    reasoning_content: Optional[ChatCompletionMessageContent] = None
    """
    The reasoning content emitted by the assistant alongside `content`.
    """
    encrypted_content: Optional[str] = None
    """
    Encrypted form of the reasoning content, when redaction is enabled.
    """
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = None
    """
    The tool calls generated by the model, such as function calls.
    """
    name: Optional[str] = None
