# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel


class ChatCompletionTokenLogprobTopLogprob(BaseModel):
    token: str
    logprob: float
    bytes: Optional[List[int]]
    """
    UTF-8 bytes for the token, or `null` when no byte representation exists.
    """
