# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict

from .image_detail import ImageDetail
from .image_pixel_limit_param import ImagePixelLimitParam


class ChatCompletionContentPartImageImageUrlParam(TypedDict, total=False):
    url: Optional[str]
    """Either a URL of the image or the base64 encoded image data."""

    detail: Optional[ImageDetail]
    """Specifies the detail level of the image. Defaults to `auto`."""

    image_pixel_limit: Optional[ImagePixelLimitParam]
    """Optional pixel-size limits for image preprocessing."""

    file_id: Optional[str]
    """The blob id of the image, when uploaded out-of-band."""
