# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from typing_extensions import Required, TypedDict

from .chat_completion_request_message_param import ChatCompletionRequestMessageParam
from .chat_completion_response_format_param import ChatCompletionResponseFormatParam
from .chat_completion_stop_param import ChatCompletionStopParam
from .chat_completion_stream_options_param import ChatCompletionStreamOptionsParam
from .chat_completion_tool_choice_param import ChatCompletionToolChoiceParam
from .chat_completion_tool_param import ChatCompletionToolParam
from .reasoning_effort import ReasoningEffort
from .request_service_tier import RequestServiceTier
from .thinking_param import ThinkingParam


class ChatCompletionRequestParam(TypedDict, total=False):
    messages: Required[List[ChatCompletionRequestMessageParam]]
    """A list of messages comprising the conversation so far."""

    model: Required[str]
    """ID of the model to use."""

    frequency_penalty: Optional[float]
    """
    Number between -2.0 and 2.0. Positive values penalize new tokens
    based on their existing frequency in the text so far.
    """

    presence_penalty: Optional[float]
    """
    Number between -2.0 and 2.0. Positive values penalize new tokens
    based on whether they appear in the text so far.
    """

    repetition_penalty: Optional[float]
    """
    Number between 0.0 and 2.0. Penalizes repetition independently of
    frequency.
    """

    logit_bias: Optional[Dict[str, float]]
    """
    Modify the likelihood of specified tokens appearing in the
    completion. Maps token IDs (as strings) to a bias from -100 to 100.
    """

    logprobs: Optional[bool]
    """Whether to return log probabilities of the output tokens."""

    top_logprobs: Optional[int]
    """
    Number of most-likely tokens to return at each position when
    `logprobs` is true. Range 0-20.
    """

    max_tokens: Optional[int]
    """
    The maximum number of tokens that can be generated in the
    completion.
    """

    max_completion_tokens: Optional[int]
    """Upper bound on completion tokens, including reasoning tokens."""

    n: Optional[int]
    """
    How many chat completion choices to generate for each input
    message. Range 1-5.
    """

    response_format: Optional[ChatCompletionResponseFormatParam]
    """An object specifying the format that the model must output."""

    stop: Optional[ChatCompletionStopParam]
    """
    Up to 4 sequences where the API will stop generating further
    tokens.
    """

    stream: Optional[bool]
    """
    If set, partial message deltas will be sent as data-only
    server-sent events.
    """

    stream_options: Optional[ChatCompletionStreamOptionsParam]
    """Options for streaming responses."""

    temperature: Optional[float]
    """What sampling temperature to use, between 0 and 2."""

    top_p: Optional[float]
    """Nucleus sampling: between 0 and 1."""

    tool_choice: Optional[ChatCompletionToolChoiceParam]
    """Controls which (if any) tool is called by the model."""

    tools: Optional[List[ChatCompletionToolParam]]
    """A list of tools the model may call."""

    parallel_tool_calls: Optional[bool]
    """Whether to enable parallel function calling during tool use."""

    user: Optional[str]
    """A unique identifier representing your end-user."""

    service_tier: Optional[RequestServiceTier]
    """The service tier to use for the request."""

    reasoning_effort: Optional[ReasoningEffort]
    """Constrains effort on reasoning."""

    thinking: Optional[ThinkingParam]
    """Configuration for thinking-mode models."""
