# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .chat_completion_message_content_param import ChatCompletionMessageContentParam


class ChatCompletionRequestToolMessageParam(TypedDict, total=False):
    role: Required[Literal["tool"]]
    """The role of the messages author. Always `tool`."""

    content: Required[ChatCompletionMessageContentParam]
    """The contents of the tool message."""

    tool_call_id: Required[str]
    """Tool call that this message is responding to."""

    name: Optional[str]
