# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .chat_completion_request_assistant_message import (
    ChatCompletionRequestAssistantMessage,
)
from .chat_completion_request_system_message import ChatCompletionRequestSystemMessage
from .chat_completion_request_tool_message import ChatCompletionRequestToolMessage
from .chat_completion_request_user_message import ChatCompletionRequestUserMessage

ChatCompletionRequestMessage = TypeAliasType(
    "ChatCompletionRequestMessage",
    Annotated[
        Union[
            ChatCompletionRequestUserMessage,
            ChatCompletionRequestSystemMessage,
            ChatCompletionRequestAssistantMessage,
            ChatCompletionRequestToolMessage,
        ],
        Field(discriminator="role"),
    ],
)
