# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List

from arkruntime._models import BaseModel

from .chat_completion_token_logprob import ChatCompletionTokenLogprob


class ChatCompletionChoiceLogprobs(BaseModel):
    content: List[ChatCompletionTokenLogprob]
    """
    A list of message content tokens with log probability information.
    """
