# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .chat_completion_content_part_video_video_url import (
    ChatCompletionContentPartVideoVideoUrl,
)


class ChatCompletionContentPartVideo(BaseModel):
    type: Literal["video_url"]
    """
    The type of the content part. Always `video_url`.
    """
    video_url: ChatCompletionContentPartVideoVideoUrl
