# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .chat_completion_message_tool_call_chunk import ChatCompletionMessageToolCallChunk


class ChatCompletionStreamResponseDelta(BaseModel):
    role: Optional[str] = None
    """
    The role of the author of this message.
    """
    content: Optional[str] = None
    """
    The contents of the chunk message.
    """
    reasoning_content: Optional[str] = None
    """
    The reasoning content delta.
    """
    encrypted_content: Optional[str] = None
    """
    Encrypted reasoning content delta.
    """
    tool_calls: Optional[List[ChatCompletionMessageToolCallChunk]] = None
    """
    The tool calls generated by the model.
    """
