# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .function_object import FunctionObject
from .tool_type import ToolType


class ChatCompletionTool(BaseModel):
    type: ToolType
    """
    The type of the tool. Currently, only `function` is supported.
    """
    function: FunctionObject
