# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .chat_completion_message_content import ChatCompletionMessageContent


class ChatCompletionRequestToolMessage(BaseModel):
    role: Literal["tool"]
    """
    The role of the messages author. Always `tool`.
    """
    content: Optional[ChatCompletionMessageContent] = None
    """
    The contents of the tool message. Missing or null content is
    normalized to an empty string.
    """
    tool_call_id: Optional[str] = None
    """
    Tool call that this message is responding to. Missing or null IDs
    are normalized to an empty string.
    """
    name: Optional[str] = None
