# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict


class ChatCompletionContentPartAudioInputAudioParam(TypedDict, total=False):
    url: Optional[str]
    """The URL of the audio to be sent to the model."""

    file_id: Optional[str]
    """The blob id of the audio, when uploaded out-of-band."""

    data: Optional[str]
    """Base64-encoded audio data."""

    format: Optional[str]
    """The format of the encoded audio data (e.g. `mp3`, `wav`)."""
