# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing_extensions import Required, TypedDict


from .chat_completion_message_tool_call_function_param import (
    ChatCompletionMessageToolCallFunctionParam,
)
from .tool_type_param import ToolTypeParam


class ChatCompletionMessageToolCallParam(TypedDict, total=False):
    id: Required[str]
    """The ID of the tool call."""

    type: Required[ToolTypeParam]
    """The type of the tool. Currently, only `function` is supported."""

    function: Required[ChatCompletionMessageToolCallFunctionParam]
    """The function that the model called."""
