# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class ChatCompletionContentPartFileFile(BaseModel):
    file_id: Optional[str] = None
    """
    The blob id of a file uploaded out-of-band.
    """
    file_url: Optional[str] = None
    """
    The URL of the file to be sent to the model.
    """
    file_data: Optional[str] = None
    """
    The base64 encoded file data, used when passing the file inline.
    """
    filename: Optional[str] = None
    """
    The name of the file, required when `file_data` is set.
    """
