# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import Annotated

from arkruntime._models import BaseModel
from pydantic import Field


class ChatCompletionResponseFormatJsonSchema(BaseModel):
    name: str
    """
    The non-empty name of the response format.
    """
    description: Optional[str] = None
    """
    A description of what the response format is for.
    """
    schema_: Annotated[Optional[object], Field(alias="schema")] = None
    """
    The JSON Schema value for the response format, preserved as raw JSON.
    """
    strict: Optional[bool] = None
    """
    Whether to enable strict schema adherence when generating the
    output.
    """
