# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .chat_completion_message_content import ChatCompletionMessageContent


class ChatCompletionRequestDeveloperMessage(BaseModel):
    """
    Developer instructions are treated as system messages.
    """

    role: Literal["developer"]
    """
    The role of the message author. Always `developer`.
    """
    content: ChatCompletionMessageContent
    """
    The contents of the developer message.
    """
    name: Optional[str] = None
