# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
from .chat_completion_role import ChatCompletionRole


class ChatCompletionResponseMessage(BaseModel):
    role: ChatCompletionRole
    """
    The role of the author of this message.
    """
    content: str
    """
    The contents of the message.
    """
    reasoning_content: Optional[str] = None
    """
    The reasoning content emitted by the model alongside `content`.
    """
    encrypted_content: Optional[str] = None
    """
    Encrypted form of the reasoning content.
    """
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = None
    """
    The tool calls generated by the model.
    """
