# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from typing_extensions import Required, TypedDict

from .chat_completion_message_content_param import ChatCompletionMessageContentParam
from .chat_completion_message_tool_call_param import ChatCompletionMessageToolCallParam


class ChatCompletionRequestAssistantMessageParam(TypedDict, total=False):
    role: Required[Literal["assistant"]]
    """The role of the messages author. Always `assistant`."""

    content: Optional[ChatCompletionMessageContentParam]
    """
    The contents of the assistant message. Required unless `tool_calls`
    is specified.
    """

    reasoning_content: Optional[ChatCompletionMessageContentParam]
    """The reasoning content emitted by the assistant alongside `content`."""

    encrypted_content: Optional[str]
    """Encrypted form of the reasoning content, when redaction is enabled."""

    tool_calls: Optional[List[ChatCompletionMessageToolCallParam]]
    """The tool calls generated by the model, such as function calls."""

    name: Optional[str]
