# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from typing_extensions import Required, TypedDict

from .chat_completion_content_part_audio_input_audio_param import (
    ChatCompletionContentPartAudioInputAudioParam,
)


class ChatCompletionContentPartAudioParam(TypedDict, total=False):
    type: Required[Literal["input_audio"]]
    """The type of the content part. Always `input_audio`."""

    input_audio: Required[ChatCompletionContentPartAudioInputAudioParam]
