# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict

from .video_image_pixel_limit_param import VideoImagePixelLimitParam


class ChatCompletionContentPartVideoVideoUrlParam(TypedDict, total=False):
    url: Optional[str]
    """Either a URL of the video or the base64 encoded video data."""

    fps: Optional[float]
    """Frames-per-second sampling rate for the video."""

    detail: Optional[str]
    """Specifies the detail level of frames extracted from the video."""

    image_pixel_limit: Optional[VideoImagePixelLimitParam]
    """Optional pixel-size limits applied to extracted frames."""

    file_id: Optional[str]
    """The blob id of the video, when uploaded out-of-band."""
