# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .completion_tokens_details import CompletionTokensDetails
from .prompt_tokens_details import PromptTokensDetails


class CompletionUsage(BaseModel):
    prompt_tokens: int
    """
    Number of tokens in the prompt.
    """
    completion_tokens: int
    """
    Number of tokens in the generated completion.
    """
    total_tokens: int
    """
    Total tokens used (prompt + completion).
    """
    prompt_tokens_details: PromptTokensDetails
    """
    A detailed breakdown of the prompt tokens.
    """
    completion_tokens_details: CompletionTokensDetails
    """
    A detailed breakdown of the completion tokens.
    """
