# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class Error(BaseModel):
    code: str
    """
    A machine-readable error code.
    """
    message: str
    """
    A human-readable description of the error.
    """
    param: str
    """
    The parameter that caused the error, if applicable.
    """
    type: str
    """
    The error type.
    """
