# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from typing_extensions import Required, TypedDict


class FunctionObjectParam(TypedDict, total=False):
    name: Required[str]
    """
    The name of the function to be called. Must be a-z, A-Z, 0-9, or
    contain underscores and dashes, with a maximum length of 64.
    """

    description: Optional[str]
    """
    A description of what the function does, used by the model to choose
    when and how to call the function.
    """

    parameters: Optional[Dict[str, object]]
    """
    The parameters the function accepts, described as a JSON Schema
    object. Omitting `parameters` defines a function with an empty
    parameter list.
    """

    strict: Optional[bool]
    """
    Whether to enable strict schema adherence when generating the function
    call.
    """
