# Copyright (c) 2025 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
# License text: https://github.com/volcengine/ark-runtime-python/blob/main/LICENSE

from typing import List, Generic, TypeVar, Optional

from ..._models import GenericModel
from .chat_completion_response import ChatCompletionResponse
from .chat_completion_response_choice import ChatCompletionResponseChoice
from .chat_completion_response_message import ChatCompletionResponseMessage
from .parsed_function_tool_call_shim import ParsedFunctionToolCall

__all__ = [
    "ParsedChatCompletion",
    "ParsedChoice",
    "ParsedChatCompletionMessage",
]


ContentType = TypeVar("ContentType")

# we need to disable this check because we're overriding properties
# with subclasses of their types which is technically unsound as
# properties can be mutated.
# pyright: reportIncompatibleVariableOverride=false


class ParsedChatCompletionMessage(
    ChatCompletionResponseMessage, GenericModel, Generic[ContentType]
):
    parsed: Optional[ContentType] = None
    """The auto-parsed message contents"""

    tool_calls: Optional[List[ParsedFunctionToolCall]] = None  # type: ignore[assignment]
    """The tool calls generated by the model, such as function calls."""


class ParsedChoice(
    ChatCompletionResponseChoice, GenericModel, Generic[ContentType]
):
    message: ParsedChatCompletionMessage[ContentType]
    """A chat completion message generated by the model."""


class ParsedChatCompletion(
    ChatCompletionResponse, GenericModel, Generic[ContentType]
):
    choices: List[ParsedChoice[ContentType]]  # type: ignore[assignment]
    """A list of chat completion choices.

    Can be more than one if `n` is greater than 1.
    """
