# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class PromptTokensDetails(BaseModel):
    cached_tokens: int
    """
    Cached prompt tokens.
    """
    text_tokens: Optional[int] = None
    """
    Prompt tokens consumed by text inputs.
    """
    image_tokens: Optional[int] = None
    """
    Prompt tokens consumed by image inputs.
    """
    audio_tokens: Optional[int] = None
    """
    Prompt tokens consumed by audio inputs.
    """
    audio_cached_tokens: Optional[int] = None
    """
    Cached prompt tokens consumed by audio inputs.
    """
