# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .doc_citation import DocCitation
from .url_citation import UrlCitation

Annotation = TypeAliasType(
    "Annotation",
    Annotated[Union[UrlCitation, DocCitation], Field(discriminator="type")],
)
