# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .clear_thinking_response import ClearThinkingResponse
from .clear_tool_uses_response import ClearToolUsesResponse

AppliedEdit = TypeAliasType(
    "AppliedEdit",
    Annotated[
        Union[ClearToolUsesResponse, ClearThinkingResponse], Field(discriminator="type")
    ],
)
