# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .clear_tool_uses_inputs import ClearToolUsesInputs
from .tool_uses_keep import ToolUsesKeep
from .tool_uses_trigger import ToolUsesTrigger


class ClearToolUses(BaseModel):
    type: Literal["clear_tool_uses"]
    clear_tool_inputs: ClearToolUsesInputs
    exclude_tools: Optional[List[str]] = None
    keep: Optional[ToolUsesKeep] = None
    trigger: Optional[ToolUsesTrigger] = None
