# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from typing_extensions import Required, TypedDict

from .clear_tool_uses_inputs_param import ClearToolUsesInputsParam
from .tool_uses_keep_param import ToolUsesKeepParam
from .tool_uses_trigger_param import ToolUsesTriggerParam


class ClearToolUsesParam(TypedDict, total=False):
    type: Required[Literal["clear_tool_uses"]]

    clear_tool_inputs: Required[ClearToolUsesInputsParam]

    exclude_tools: Optional[List[str]]

    keep: Optional[ToolUsesKeepParam]

    trigger: Optional[ToolUsesTriggerParam]
