# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from typing_extensions import Required, TypedDict

from .clear_thinking_keep_param import ClearThinkingKeepParam


class ClearThinkingParam(TypedDict, total=False):
    type: Required[Literal["clear_thinking"]]

    keep: Required[ClearThinkingKeepParam]
