# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .audio_chunking_strategy_param import AudioChunkingStrategyParam


class ContentItemAudioParam(TypedDict, total=False):
    type: Required[Literal["input_audio"]]

    chunking_strategy: Optional[AudioChunkingStrategyParam]

    audio_url: Optional[str]

    file_id: Optional[str]
