# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import TypeAlias, Union

from .content_item_audio_param import ContentItemAudioParam
from .content_item_file_param import ContentItemFileParam
from .content_item_image_param import ContentItemImageParam
from .content_item_text_param import ContentItemTextParam
from .content_item_video_param import ContentItemVideoParam
from .output_content_item_reasoning_text_param import (
    OutputContentItemReasoningTextParam,
)
from .output_content_item_text_param import OutputContentItemTextParam

ContentItemParam: TypeAlias = Union[
    ContentItemTextParam,
    ContentItemImageParam,
    ContentItemAudioParam,
    ContentItemFileParam,
    ContentItemVideoParam,
    OutputContentItemTextParam,
    OutputContentItemReasoningTextParam,
]
