# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .image_detail import ImageDetail
from .image_pixel_limit import ImagePixelLimit


class ContentItemImage(BaseModel):
    type: Literal["input_image"]
    image_url: Optional[str] = None
    file_id: Optional[str] = None
    detail: Optional[ImageDetail] = None
    image_pixel_limit: Optional[ImagePixelLimit] = None
