# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict


class ContentItemVideoParam(TypedDict, total=False):
    type: Required[Literal["input_video"]]
    """The type of the input item. Always `input_video`."""

    video_url: Required[str]
    """The URL of the video to be sent to the model. A fully qualified URL or base64 encoded video in a data URL."""

    file_id: Optional[str]

    fps: Optional[float]
    """Extract a specified number of images from the video every second."""
