# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .content_item_audio import ContentItemAudio
from .content_item_file import ContentItemFile
from .content_item_image import ContentItemImage
from .content_item_text import ContentItemText
from .content_item_video import ContentItemVideo
from .output_content_item_reasoning_text import OutputContentItemReasoningText
from .output_content_item_text import OutputContentItemText

ContentItem = TypeAliasType(
    "ContentItem",
    Annotated[
        Union[
            ContentItemText,
            ContentItemImage,
            ContentItemAudio,
            ContentItemFile,
            ContentItemVideo,
            OutputContentItemText,
            OutputContentItemReasoningText,
        ],
        Field(discriminator="type"),
    ],
)
