# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Literal, Optional

from arkruntime._models import BaseModel


class DocCitation(BaseModel):
    type: Literal["doc_citation"]
    doc_id: Optional[str] = None
    doc_name: Optional[str] = None
    chunk_id: Optional[int] = None
    chunk_attachment: Optional[List[Dict[str, object]]] = None
