# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Literal, Optional

from typing_extensions import Required, TypedDict


class DocCitationParam(TypedDict, total=False):
    type: Required[Literal["doc_citation"]]

    doc_id: Optional[str]

    doc_name: Optional[str]

    chunk_id: Optional[int]

    chunk_attachment: Optional[List[Dict[str, object]]]
