# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .item_status import ItemStatus


class DoubaoAppCallBlockReasoningText(BaseModel):
    type: Literal["reasoning_text"]
    id: Optional[str] = None
    reasoning_text: Optional[str] = None
    status: Optional[ItemStatus] = None
    parent_id: Optional[str] = None
