# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict

from .doubao_app_feature_item_param import DoubaoAppFeatureItemParam


class DoubaoAppFeatureParam(TypedDict, total=False):
    chat: Optional[DoubaoAppFeatureItemParam]

    deep_chat: Optional[DoubaoAppFeatureItemParam]

    ai_search: Optional[DoubaoAppFeatureItemParam]

    reasoning_search: Optional[DoubaoAppFeatureItemParam]
