# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .doubao_app_feature_param import DoubaoAppFeatureParam
from .user_location_param import UserLocationParam


class DoubaoAppToolParam(TypedDict, total=False):
    type: Required[Literal["doubao_app"]]

    feature: Required[DoubaoAppFeatureParam]

    user_location: Optional[UserLocationParam]
