# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .doubao_app_search_result import DoubaoAppSearchResult
from .item_status import ItemStatus


class DoubaoAppCallBlockReasoningSearch(BaseModel):
    type: Literal["reasoning_search"]
    id: Optional[str] = None
    summary: Optional[str] = None
    queries: Optional[List[str]] = None
    results: Optional[List[DoubaoAppSearchResult]] = None
    status: Optional[ItemStatus] = None
    parent_id: Optional[str] = None
