# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .clear_thinking import ClearThinking
from .clear_tool_uses import ClearToolUses

Edit = TypeAliasType(
    "Edit", Annotated[Union[ClearToolUses, ClearThinking], Field(discriminator="type")]
)
