# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .content_filter import ContentFilter


class IncompleteDetails(BaseModel):
    reason: str
    """
    The reason why the response is incomplete.
    """
    content_filter: Optional[ContentFilter] = None
    """
    The content filter details.
    """
