# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from typing_extensions import TypeAlias

from .item_easy_message_param import ItemEasyMessageParam
from .item_function_mcp_approval_request_param import (
    ItemFunctionMcpApprovalRequestParam,
)
from .item_function_mcp_approval_response_param import (
    ItemFunctionMcpApprovalResponseParam,
)
from .item_function_mcp_call_param import ItemFunctionMcpCallParam
from .item_function_mcp_list_tools_param import ItemFunctionMcpListToolsParam
from .item_function_tool_call_output_param import ItemFunctionToolCallOutputParam
from .item_function_tool_call_param import ItemFunctionToolCallParam
from .item_reasoning_param import ItemReasoningParam

InputItemParam: TypeAlias = Union[
    ItemEasyMessageParam,
    ItemFunctionToolCallParam,
    ItemFunctionToolCallOutputParam,
    ItemReasoningParam,
    ItemFunctionMcpApprovalRequestParam,
    ItemFunctionMcpApprovalResponseParam,
    ItemFunctionMcpListToolsParam,
    ItemFunctionMcpCallParam,
]
