# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .item_easy_message import ItemEasyMessage
from .item_function_mcp_approval_request import ItemFunctionMcpApprovalRequest
from .item_function_mcp_approval_response import ItemFunctionMcpApprovalResponse
from .item_function_mcp_call import ItemFunctionMcpCall
from .item_function_mcp_list_tools import ItemFunctionMcpListTools
from .item_function_tool_call import ItemFunctionToolCall
from .item_function_tool_call_output import ItemFunctionToolCallOutput
from .item_reasoning import ItemReasoning

InputItem = TypeAliasType(
    "InputItem",
    Annotated[
        Union[
            ItemEasyMessage,
            ItemFunctionToolCall,
            ItemFunctionToolCallOutput,
            ItemReasoning,
            ItemFunctionMcpApprovalRequest,
            ItemFunctionMcpApprovalResponse,
            ItemFunctionMcpListTools,
            ItemFunctionMcpCall,
        ],
        Field(discriminator="type"),
    ],
)
