# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from typing_extensions import Required, TypedDict

from .item_status import ItemStatus
from .output_content_item_param import OutputContentItemParam
from .reasoning_summary_part_param import ReasoningSummaryPartParam


class ItemReasoningParam(TypedDict, total=False):
    id: Optional[str]

    type: Required[Literal["reasoning"]]

    status: Required[ItemStatus]

    summary: Optional[List[ReasoningSummaryPartParam]]

    content: Optional[List[OutputContentItemParam]]

    encrypted_content: Optional[str]
