# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from arkruntime._models import BaseModel

from .item_status import ItemStatus
from .response_image_process_action import ResponseImageProcessAction
from .response_image_process_error import ResponseImageProcessError


class ItemFunctionImageProcess(BaseModel):
    type: Literal["image_process"]
    action: Optional[ResponseImageProcessAction] = None
    arguments: Optional[Dict[str, object]] = None
    status: ItemStatus
    id: str
    error: Optional[ResponseImageProcessError] = None
