# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict


class ItemFunctionMcpCallParam(TypedDict, total=False):
    type: Required[Literal["mcp_call"]]
    """The type of the item. Always `mcp_call`."""

    server_label: Required[str]
    """The label of the MCP server running the tool."""

    arguments: Optional[str]
    """
    A JSON string of the arguments passed to the tool. Streamed in via
    `response.mcp_call_arguments.delta` so it may be absent on the initial
    `output_item.added` event.
    """

    name: Required[str]
    """The name of the tool that was run."""

    id: Optional[str]
    """The unique ID of the tool call."""

    error: Optional[str]
    """The error from the tool call, if any."""

    output: Optional[str]
    """The output from the tool call."""
