# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ItemFunctionMcpApprovalResponse(BaseModel):
    id: Optional[str] = None
    """
    The unique ID of the approval response
    """
    approval_request_id: str
    """
    The ID of the approval request being answered.
    """
    approve: bool
    """
    Whether the request was approved.
    """
    type: Literal["mcp_approval_response"]
    """
    The type of the item. Always `mcp_approval_response`.
    """
    reason: Optional[str] = None
    """
    Optional reason for the decision.
    """
