# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .message_content import MessageContent
from .message_role import MessageRole


class ItemEasyMessage(BaseModel):
    type: Optional[Literal["message"]] = "message"
    role: Optional[MessageRole] = None
    content: MessageContent
    id: Optional[str] = None
    partial: Optional[bool] = None
