# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .item_status import ItemStatus
from .output_content_item import OutputContentItem


class ItemOutputMessage(BaseModel):
    type: Literal["message"]
    role: Literal["assistant"]
    content: Optional[List[OutputContentItem]] = None
    status: ItemStatus
    id: str
    partial: Optional[bool] = None
