# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ItemFunctionMcpApprovalRequest(BaseModel):
    type: Literal["mcp_approval_request"]
    """
    The type of the item. Always `mcp_approval_request`.
    """
    server_label: str
    """
    The label of the MCP server making the request.
    """
    arguments: str
    """
    A JSON string of arguments for the tool.
    """
    name: str
    """
    The name of the tool to run.
    """
    id: Optional[str] = None
    """
    The unique ID of the approval request.
    """
