# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from typing_extensions import Required, TypedDict

from .mcp_list_tools_tool_param import McpListToolsToolParam


class ItemFunctionMcpListToolsParam(TypedDict, total=False):
    type: Required[Literal["mcp_list_tools"]]
    """The type of the item. Always `mcp_list_tools`."""

    server_label: Required[str]
    """The label of the MCP server."""

    tools: Optional[List[McpListToolsToolParam]]
    """The tools available on the server."""

    id: Optional[str]
    """The unique ID of the list."""

    error: Optional[str]
    """Error message if the server could not list tools."""
