# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .content_item import ContentItem
from .item_status import ItemStatus
from .message_role import MessageRole


class ItemInputMessage(BaseModel):
    type: Optional[Literal["message"]] = "message"
    role: MessageRole
    content: List[ContentItem]
    status: Optional[ItemStatus] = None
    id: Optional[str] = None
    partial: Optional[bool] = None
