# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .item_status import ItemStatus
from .message_content_param import MessageContentParam


class ItemFunctionToolCallOutputParam(TypedDict, total=False):
    type: Required[Literal["function_call_output"]]

    call_id: Optional[str]

    output: Optional[MessageContentParam]

    id: Optional[str]

    status: Optional[ItemStatus]
