# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .item_status import ItemStatus
from .web_search_action import WebSearchAction


class ItemFunctionWebSearch(BaseModel):
    type: Literal["web_search_call"]
    action: Optional[WebSearchAction] = None
    status: ItemStatus
    id: str
