# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .mcp_list_tools_tool import McpListToolsTool


class ItemFunctionMcpListTools(BaseModel):
    type: Literal["mcp_list_tools"]
    """
    The type of the item. Always `mcp_list_tools`.
    """
    server_label: str
    """
    The label of the MCP server.
    """
    tools: Optional[List[McpListToolsTool]] = None
    """
    The tools available on the server.
    """
    id: Optional[str] = None
    """
    The unique ID of the list.
    """
    error: Optional[str] = None
    """
    Error message if the server could not list tools.
    """
