# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .item_status import ItemStatus
from .message_content import MessageContent


class ItemFunctionToolCallOutput(BaseModel):
    type: Literal["function_call_output"]
    call_id: Optional[str] = None
    output: Optional[MessageContent] = None
    id: Optional[str] = None
    status: Optional[ItemStatus] = None
