# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .item_status import ItemStatus
from .transcription_part import TranscriptionPart


class ItemTranscription(BaseModel):
    id: Optional[str] = None
    type: Literal["transcription"]
    transcription: Optional[List[TranscriptionPart]] = None
    status: ItemStatus
