# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .item_status import ItemStatus


class ItemFunctionToolCallParam(TypedDict, total=False):
    id: Optional[str]
    """The unique ID of the function tool call."""

    type: Required[Literal["function_call"]]

    arguments: Optional[str]
    """A JSON string of the arguments passed to the function."""

    call_id: Optional[str]
    """The ID of the call that produced this tool call."""

    name: Optional[str]
    """The name of the function to call."""

    status: Optional[ItemStatus]
    """The status of the item."""
