# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from arkruntime._models import BaseModel


class KnowledgeSearchTool(BaseModel):
    type: Literal["knowledge_search"]
    """
    The type of the knowledge search. Always `knowledge_search`.
    """
    knowledge_resource_id: str
    """
    The knowledge base id
    """
    description: Optional[str] = None
    """
    Description of the content of the knowledge base
    """
    limit: Optional[int] = None
    """
    The maximum number of results to return. Defaults to 3.
    """
    dense_weight: Optional[float] = None
    """
    Knowledge search dense_weight
    """
    doc_filter: Optional[Dict[str, object]] = None
    """
    Knowledge search filter
    """
    ranking_options: Optional[Dict[str, object]] = None
    """
    Knowledge search ranking options
    """
    max_keyword: Optional[int] = None
    """
    Max number of keywords to search per knowledge search call
    """
