# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .input_item import InputItem


class ListInputItemsResponse(BaseModel):
    object: Literal["list"]
    data: List[InputItem]
    first_id: str
    last_id: str
    has_more: Optional[bool] = None
