# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from typing_extensions import Required, TypedDict

from .mcp_allowed_tools_param import McpAllowedToolsParam
from .mcp_require_approval_param import McpRequireApprovalParam


class McpToolParam(TypedDict, total=False):
    type: Required[Literal["mcp"]]

    server_label: Required[str]

    server_url: Required[str]

    allowed_tools: Optional[McpAllowedToolsParam]

    headers: Optional[Dict[str, str]]

    require_approval: Optional[McpRequireApprovalParam]

    server_description: Optional[str]
