# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict

from .mcp_tool_approval_filter_always_param import McpToolApprovalFilterAlwaysParam
from .mcp_tool_approval_filter_never_param import McpToolApprovalFilterNeverParam


class McpToolApprovalFilterParam(TypedDict, total=False):
    always: Optional[McpToolApprovalFilterAlwaysParam]

    never: Optional[McpToolApprovalFilterNeverParam]
