# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from typing_extensions import Required, TypedDict


class McpListToolsToolParam(TypedDict, total=False):
    name: Required[str]
    """The name of the tool."""

    description: Optional[str]
    """The description of the tool."""

    input_schema: Optional[Dict[str, object]]
    """The JSON schema describing the tool's input."""

    annotations: Optional[Dict[str, object]]
    """Additional annotations about the tool."""
