# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal, Optional

from arkruntime._models import BaseModel

from .mcp_allowed_tools import McpAllowedTools
from .mcp_require_approval import McpRequireApproval


class McpTool(BaseModel):
    type: Literal["mcp"]
    server_label: str
    server_url: str
    allowed_tools: Optional[McpAllowedTools] = None
    headers: Optional[Dict[str, str]] = None
    require_approval: Optional[McpRequireApproval] = None
    server_description: Optional[str] = None
