# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import TypeAlias, Union

from .mcp_approval_mode import McpApprovalMode
from .mcp_tool_approval_filter_param import McpToolApprovalFilterParam

McpRequireApprovalParam: TypeAlias = Union[McpApprovalMode, McpToolApprovalFilterParam]
