# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel


class McpListToolsTool(BaseModel):
    name: str
    """
    The name of the tool.
    """
    description: Optional[str] = None
    """
    The description of the tool.
    """
    input_schema: Optional[Dict[str, object]] = None
    """
    The JSON schema describing the tool's input.
    """
    annotations: Optional[Dict[str, object]] = None
    """
    Additional annotations about the tool.
    """
