# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .output_content_item_reasoning_text import OutputContentItemReasoningText
from .output_content_item_text import OutputContentItemText

OutputContentItem = TypeAliasType(
    "OutputContentItem",
    Annotated[
        Union[OutputContentItemText, OutputContentItemReasoningText],
        Field(discriminator="type"),
    ],
)
