# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from typing_extensions import Required, TypedDict

from .annotation_param import AnnotationParam


class OutputContentItemTextParam(TypedDict, total=False):
    type: Required[Literal["output_text"]]

    text: Optional[str]

    annotations: Optional[List[AnnotationParam]]
