# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from typing_extensions import TypeAlias

from .output_content_item_reasoning_text_param import (
    OutputContentItemReasoningTextParam,
)
from .output_content_item_text_param import OutputContentItemTextParam

OutputContentItemParam: TypeAlias = Union[
    OutputContentItemTextParam, OutputContentItemReasoningTextParam
]
