# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .item_agent_tool_call import ItemAgentToolCall
from .item_doubao_app_call import ItemDoubaoAppCall
from .item_function_image_process import ItemFunctionImageProcess
from .item_function_knowledge_search import ItemFunctionKnowledgeSearch
from .item_function_mcp_approval_request import ItemFunctionMcpApprovalRequest
from .item_function_mcp_call import ItemFunctionMcpCall
from .item_function_mcp_list_tools import ItemFunctionMcpListTools
from .item_function_tool_call import ItemFunctionToolCall
from .item_function_web_search import ItemFunctionWebSearch
from .item_output_message import ItemOutputMessage
from .item_reasoning import ItemReasoning
from .item_transcription import ItemTranscription

OutputItem = TypeAliasType(
    "OutputItem",
    Annotated[
        Union[
            ItemOutputMessage,
            ItemFunctionToolCall,
            ItemReasoning,
            ItemTranscription,
            ItemFunctionWebSearch,
            ItemFunctionImageProcess,
            ItemFunctionMcpApprovalRequest,
            ItemFunctionMcpListTools,
            ItemFunctionMcpCall,
            ItemFunctionKnowledgeSearch,
            ItemDoubaoAppCall,
            ItemAgentToolCall,
        ],
        Field(discriminator="type"),
    ],
)
