# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseFunctionCallArgumentsDeltaEvent(BaseModel):
    type: Literal["response.function_call_arguments.delta"]
    """
    The type of the event. Always `response.function_call_arguments.delta`.
    """
    delta: Optional[str] = None
    """
    The function-call arguments delta that is added.
    """
    item_id: str
    """
    The ID of the output item that the function-call arguments delta is added to.
    """
    output_index: int
    """
    The index of the output item that the function-call arguments delta is added to.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
