# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class ResponseWebSearchCallCompletedEvent(BaseModel):
    type: Literal["response.web_search_call.completed"]
    """
    The type of the event. Always `response.web_search_call.completed`.
    """
    item_id: str
    """
    The ID of the item this event is associated with.
    """
    output_index: int
    """
    The index of the output item this event is associated with.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
