# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .context_management import ContextManagement
from .reasoning import Reasoning
from .response_caching import ResponseCaching
from .response_includable import ResponseIncludable
from .response_text_config import ResponseTextConfig
from .responses_input import ResponsesInput
from .service_tier import ServiceTier
from .session import Session
from .thinking import Thinking
from .tool import Tool
from .tool_choice import ToolChoice


class ResponsesRequest(BaseModel):
    input: ResponsesInput
    model: str
    max_output_tokens: Optional[int] = None
    previous_response_id: Optional[str] = None
    thinking: Optional[Thinking] = None
    service_tier: Optional[ServiceTier] = None
    store: Optional[bool] = None
    stream: Optional[bool] = None
    temperature: Optional[float] = None
    tools: Optional[List[Tool]] = None
    top_p: Optional[float] = None
    instructions: Optional[str] = None
    include: Optional[List[ResponseIncludable]] = None
    caching: Optional[ResponseCaching] = None
    text: Optional[ResponseTextConfig] = None
    expire_at: Optional[int] = None
    tool_choice: Optional[ToolChoice] = None
    parallel_tool_calls: Optional[bool] = None
    max_tool_calls: Optional[int] = None
    reasoning: Optional[Reasoning] = None
    context_management: Optional[ContextManagement] = None
    session: Optional[Session] = None
    prompt_cache_key: Optional[str] = None
    safety_identifier: Optional[str] = None
