# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal

from arkruntime._models import BaseModel

from .response_image_process_action import ResponseImageProcessAction


class ResponseImageProcessCallProcessingEvent(BaseModel):
    type: Literal["response.image_process_call.progressing"]
    item_id: str
    output_index: int
    action: ResponseImageProcessAction
    arguments: Dict[str, object]
    sequence_number: int
