# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class ResponseMcpListToolsInProgressEvent(BaseModel):
    type: Literal["response.mcp_list_tools.in_progress"]
    """
    The type of the event. Always 'response.mcp_list_tools.in_progress'.
    """
    item_id: str
    """
    The ID of the MCP tool call item that is being processed.
    """
    output_index: int
    """
    The index of the output item that is being processed.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
