# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .doubao_app_search_result import DoubaoAppSearchResult


class ResponseDoubaoAppCallReasoningSearchCompletedEvent(BaseModel):
    type: Literal["response.doubao_app_call_reasoning_search.completed"]
    item_id: str
    output_index: int
    block_index: Optional[int] = None
    summary: Optional[str] = None
    queries: List[str]
    results: List[DoubaoAppSearchResult]
    sequence_number: int
