# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .output_content_item import OutputContentItem


class ResponseContentPartDoneEvent(BaseModel):
    type: Literal["response.content_part.done"]
    content_index: int
    item_id: str
    output_index: int
    part: OutputContentItem
    sequence_number: int
