# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .item_function_mcp_approval_request import ItemFunctionMcpApprovalRequest


class ResponseMcpApprovalRequestEvent(BaseModel):
    type: Literal["response.mcp_approval_request"]
    function_mcp_approval_request: ItemFunctionMcpApprovalRequest
    output_index: int
    sequence_number: int
