# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseDoubaoAppCallOutputTextDeltaEvent(BaseModel):
    type: Literal["response.doubao_app_call_output_text.delta"]
    item_id: str
    output_index: int
    block_index: Optional[int] = None
    delta: Optional[str] = None
    sequence_number: int
