# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .input_tokens_details import InputTokensDetails
from .output_tokens_details import OutputTokensDetails
from .tool_usage import ToolUsage
from .tool_usage_details import ToolUsageDetails


class ResponseUsage(BaseModel):
    input_tokens: int
    """
    The number of input tokens.
    """
    output_tokens: int
    """
    The number of output tokens.
    """
    total_tokens: int
    """
    The total number of tokens used.
    """
    input_tokens_details: InputTokensDetails
    """
    A detailed breakdown of the input tokens.
    """
    output_tokens_details: OutputTokensDetails
    """
    A detailed breakdown of the output tokens.
    """
    tool_usage: Optional[ToolUsage] = None
    """
    The usage of tools.
    """
    tool_usage_details: Optional[ToolUsageDetails] = None
    """
    A detailed breakdown of the tool usage.
    """
