# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .response import Response


class ResponseFailedEvent(BaseModel):
    type: Literal["response.failed"]
    """
    The type of the event. Always `response.failed`.
    """
    response: Response
    """
    The response that failed.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
