# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseTranscriptionTextDeltaEvent(BaseModel):
    type: Literal["response.transcription_text.delta"]
    """
    The type of the event. Always `response.transcription_text.delta`.
    """
    transcription_index: int
    """
    The index of the transcription that the text delta was added to.
    """
    delta: Optional[str] = None
    """
    The transcription text delta that was added.
    """
    item_id: str
    """
    The ID of the output item that the transcription text delta was added to.
    """
    output_index: int
    """
    The index of the output item that the transcription text delta was added to.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
    start_time: int
    """
    The start time of this transcription chunk in milliseconds.
    """
    end_time: int
    """
    The end time of this transcription chunk in milliseconds.
    """
