# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseFunctionCallArgumentsDoneEvent(BaseModel):
    type: Literal["response.function_call_arguments.done"]
    arguments: Optional[str] = None
    """
    The function-call arguments.
    """
    item_id: str
    """
    The ID of the item.
    """
    output_index: int
    """
    The index of the output item.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
