# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from typing_extensions import Required, TypedDict

from .context_management_param import ContextManagementParam
from .reasoning_param import ReasoningParam
from .response_caching_param import ResponseCachingParam
from .response_includable import ResponseIncludable
from .response_text_config_param import ResponseTextConfigParam
from .responses_input_param import ResponsesInputParam
from .service_tier import ServiceTier
from .session_param import SessionParam
from .thinking_param import ThinkingParam
from .tool_choice_param import ToolChoiceParam
from .tool_param import ToolParam


class ResponsesRequestParam(TypedDict, total=False):
    input: Required[ResponsesInputParam]

    model: Required[str]

    max_output_tokens: Optional[int]

    previous_response_id: Optional[str]

    thinking: Optional[ThinkingParam]

    service_tier: Optional[ServiceTier]

    store: Optional[bool]

    stream: Optional[bool]

    temperature: Optional[float]

    tools: Optional[List[ToolParam]]

    top_p: Optional[float]

    instructions: Optional[str]

    include: Optional[List[ResponseIncludable]]

    caching: Optional[ResponseCachingParam]

    text: Optional[ResponseTextConfigParam]

    expire_at: Optional[int]

    tool_choice: Optional[ToolChoiceParam]

    parallel_tool_calls: Optional[bool]

    max_tool_calls: Optional[int]

    reasoning: Optional[ReasoningParam]

    context_management: Optional[ContextManagementParam]

    session: Optional[SessionParam]

    prompt_cache_key: Optional[str]

    safety_identifier: Optional[str]
