# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .output_item import OutputItem


class ResponseOutputItemAddedEvent(BaseModel):
    type: Literal["response.output_item.added"]
    output_index: int
    item: OutputItem
    sequence_number: int
