# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .context_management_response import ContextManagementResponse
from .incomplete_details import IncompleteDetails
from .output_item import OutputItem
from .reasoning import Reasoning
from .response_caching import ResponseCaching
from .response_error import ResponseError
from .response_status import ResponseStatus
from .response_text_config import ResponseTextConfig
from .response_usage import ResponseUsage
from .service_tier import ServiceTier
from .session import Session
from .thinking import Thinking
from .tool import Tool
from .tool_choice import ToolChoice


class Response(BaseModel):
    created_at: int
    error: Optional[ResponseError] = None
    id: str
    incomplete_details: Optional[IncompleteDetails] = None
    max_output_tokens: Optional[int] = None
    model: str
    object: Literal["response"]
    output: Optional[List[OutputItem]] = None
    previous_response_id: Optional[str] = None
    thinking: Optional[Thinking] = None
    service_tier: Optional[ServiceTier] = None
    status: Optional[ResponseStatus] = None
    temperature: Optional[float] = None
    tools: Optional[List[Tool]] = None
    top_p: Optional[float] = None
    usage: Optional[ResponseUsage] = None
    caching: Optional[ResponseCaching] = None
    text: Optional[ResponseTextConfig] = None
    instructions: Optional[str] = None
    store: Optional[bool] = None
    expire_at: Optional[int] = None
    tool_choice: Optional[ToolChoice] = None
    parallel_tool_calls: Optional[bool] = None
    max_tool_calls: Optional[int] = None
    reasoning: Optional[Reasoning] = None
    context_management: Optional[ContextManagementResponse] = None
    session: Optional[Session] = None
    safety_identifier: Optional[str] = None
    prompt_cache_key: Optional[str] = None
