# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .transcription_part import TranscriptionPart


class ResponseTranscriptionPartAddedEvent(BaseModel):
    type: Literal["response.transcription_part.added"]
    item_id: str
    output_index: int
    transcription_index: int
    part: TranscriptionPart
    sequence_number: int
