# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseReasoningRawTextDoneEvent(BaseModel):
    type: Literal["response.reasoning_raw_text.done"]
    """
    The type of the event. Always `response.reasoning_raw_text.done`.
    """
    content_index: int
    """
    The index of the content part that the raw reasoning text is finalized.
    """
    item_id: str
    """
    The ID of the output item that the raw reasoning text is finalized.
    """
    output_index: int
    """
    The index of the output item that the raw reasoning text is finalized.
    """
    text: Optional[str] = None
    """
    The raw reasoning text content that is finalized.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
