# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseReasoningSummaryTextDeltaEvent(BaseModel):
    type: Literal["response.reasoning_summary_text.delta"]
    """
    The type of the event. Always `response.reasoning_summary_text.delta`.
    """
    delta: Optional[str] = None
    """
    The text delta that was added to the summary.
    """
    item_id: str
    """
    The ID of the item this summary text delta is associated with.
    """
    output_index: int
    """
    The index of the output item this summary text delta is associated with.
    """
    summary_index: int
    """
    The index of the summary part within the reasoning summary.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
