# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class ResponseReasoningTextDeltaEvent(BaseModel):
    type: Literal["response.reasoning_text.delta"]
    """
    The type of the event. Always `response.reasoning_text.delta`.
    """
    content_index: int
    """
    The index of the content part that the reasoning text delta was added to.
    """
    delta: Optional[str] = None
    """
    The reasoning text delta that was added.
    """
    item_id: str
    """
    The ID of the output item that the reasoning text delta was added to.
    """
    output_index: int
    """
    The index of the output item that the reasoning text delta was added to.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
