# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .audio_chunk import AudioChunk


class ResponseTranscriptionTextDoneEvent(BaseModel):
    type: Literal["response.transcription_text.done"]
    """
    The type of the event. Always `response.transcription_text.done`.
    """
    transcription_index: int
    """
    The index of the transcription that the text content is finalized.
    """
    item_id: str
    """
    The ID of the output item that the transcription text is finalized.
    """
    output_index: int
    """
    The index of the output item that the transcription text is finalized.
    """
    text: Optional[str] = None
    """
    The transcription text content that is finalized.
    """
    start_time: int
    """
    The start time of this transcription chunk in milliseconds.
    """
    end_time: int
    """
    The end time of this transcription chunk in milliseconds.
    """
    chunks: List[AudioChunk]
    """
    Audio chunks associated with this finalized transcription.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
