# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .doubao_app_call_block import DoubaoAppCallBlock


class ResponseDoubaoAppCallBlockAddedEvent(BaseModel):
    type: Literal["response.doubao_app_call_block.added"]
    item_id: str
    output_index: int
    sequence_number: int
    block: DoubaoAppCallBlock
