# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .annotation import Annotation


class ResponseOutputTextAnnotationAddedEvent(BaseModel):
    type: Literal["response.output_text.annotation.added"]
    """
    The type of the event. Always `response.output_text.annotation.added`.
    """
    content_index: int
    """
    The index of the content part that the annotation was added to.
    """
    item_id: str
    """
    The ID of the output item that the annotation was added to.
    """
    output_index: int
    """
    The index of the output item that the annotation was added to.
    """
    annotation_index: Optional[int] = None
    """
    The index of the annotation within the content part's annotation list.
    Optional: server omits when emitting per-annotation events that don't
    carry an explicit positional index.
    """
    annotation: Annotation
    """
    The annotation that was added.
    """
    sequence_number: int
    """
    The sequence number of this event.
    """
