# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Dict, Optional

from arkruntime._models import BaseModel
from pydantic import Field

from .text_format_type import TextFormatType


class TextFormat(BaseModel):
    type: TextFormatType
    schema_: Annotated[Optional[Dict[str, object]], Field(alias="schema")] = None
    name: Optional[str] = None
    description: Optional[str] = None
    strict: Optional[bool] = None
