# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from typing_extensions import Required, TypedDict

from .text_format_type import TextFormatType


class TextFormatParam(TypedDict, total=False):
    type: Required[TextFormatType]

    schema: Optional[Dict[str, object]]

    name: Optional[str]

    description: Optional[str]

    strict: Optional[bool]
