# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import TypeAlias, Union

from .doubao_app_tool_param import DoubaoAppToolParam
from .function_tool_param import FunctionToolParam
from .image_process_tool_param import ImageProcessToolParam
from .knowledge_search_tool_param import KnowledgeSearchToolParam
from .mcp_tool_param import McpToolParam
from .web_search_tool_param import WebSearchToolParam

ToolParam: TypeAlias = Union[
    FunctionToolParam,
    WebSearchToolParam,
    ImageProcessToolParam,
    McpToolParam,
    KnowledgeSearchToolParam,
    DoubaoAppToolParam,
]
