# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Optional

from arkruntime._models import BaseModel


class ToolUsageDetails(BaseModel):
    web_search: Optional[Dict[str, object]] = None
    """
    The usage of web search tools.
    """
    mcp: Optional[Dict[str, object]] = None
    """
    The usage of MCP tools.
    """
    knowledge_search: Optional[Dict[str, object]] = None
    """
    The usage of knowledge search tools.
    """
    doubao_app: Optional[Dict[str, object]] = None
    """
    The usage of doubao app tools.
    """
