# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict


class ToolChoiceMcpParam(TypedDict, total=False):
    type: Required[Literal["mcp"]]
    """For MCP tools, the type is always `mcp`."""

    server_label: Required[str]
    """The label of the MCP server to use."""

    name: Optional[str]
    """The name of the tool to call on the server."""
