# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .doubao_app_tool import DoubaoAppTool
from .function_tool import FunctionTool
from .image_process_tool import ImageProcessTool
from .knowledge_search_tool import KnowledgeSearchTool
from .mcp_tool import McpTool
from .web_search_tool import WebSearchTool

Tool = TypeAliasType(
    "Tool",
    Annotated[
        Union[
            FunctionTool,
            WebSearchTool,
            ImageProcessTool,
            McpTool,
            KnowledgeSearchTool,
            DoubaoAppTool,
        ],
        Field(discriminator="type"),
    ],
)
