# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .tool_choice_function import ToolChoiceFunction
from .tool_choice_knowledge_search import ToolChoiceKnowledgeSearch
from .tool_choice_mcp import ToolChoiceMcp
from .tool_choice_web_search import ToolChoiceWebSearch

TypedToolChoice = TypeAliasType(
    "TypedToolChoice",
    Annotated[
        Union[
            ToolChoiceFunction,
            ToolChoiceMcp,
            ToolChoiceWebSearch,
            ToolChoiceKnowledgeSearch,
        ],
        Field(discriminator="type"),
    ],
)
