# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from typing_extensions import TypeAlias

from .tool_choice_function_param import ToolChoiceFunctionParam
from .tool_choice_knowledge_search_param import ToolChoiceKnowledgeSearchParam
from .tool_choice_mcp_param import ToolChoiceMcpParam
from .tool_choice_web_search_param import ToolChoiceWebSearchParam

TypedToolChoiceParam: TypeAlias = Union[
    ToolChoiceFunctionParam,
    ToolChoiceMcpParam,
    ToolChoiceWebSearchParam,
    ToolChoiceKnowledgeSearchParam,
]
