# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Required, TypedDict

from .cover_image_param import CoverImageParam


class UrlCitationParam(TypedDict, total=False):
    type: Required[Literal["url_citation"]]

    title: Required[str]

    url: Required[str]

    logo_url: Optional[str]

    mobile_url: Optional[str]

    site_name: Optional[str]

    publish_time: Optional[str]

    cover_image: Optional[CoverImageParam]

    summary: Optional[str]

    freshness_info: Optional[str]
