# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .cover_image import CoverImage


class UrlCitation(BaseModel):
    type: Literal["url_citation"]
    title: str
    url: str
    logo_url: Optional[str] = None
    mobile_url: Optional[str] = None
    site_name: Optional[str] = None
    publish_time: Optional[str] = None
    cover_image: Optional[CoverImage] = None
    summary: Optional[str] = None
    freshness_info: Optional[str] = None
