# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class UserLocation(BaseModel):
    type: Literal["approximate"]
    """
    The type of the user location. Always `approximate`.
    """
    city: Optional[str] = None
    """
    The city of the user location.
    """
    country: Optional[str] = None
    """
    The country of the user location.
    """
    region: Optional[str] = None
    """
    The region of the user location.
    """
    timezone: Optional[float] = None
    """
    The timezone of the user location.
    """
