# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .user_location import UserLocation
from .web_search_source import WebSearchSource


class WebSearchTool(BaseModel):
    type: Literal["web_search"]
    limit: Optional[int] = None
    user_location: Optional[UserLocation] = None
    sources: Optional[List[WebSearchSource]] = None
    max_keyword: Optional[int] = None
