# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class WebSearchSource(str, Enum):
    toutiao = "toutiao"
    douyin = "douyin"
    moji = "moji"
    search_engine = "search_engine"
