# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from typing_extensions import Required, TypedDict

from .user_location_param import UserLocationParam
from .web_search_source import WebSearchSource


class WebSearchToolParam(TypedDict, total=False):
    type: Required[Literal["web_search"]]

    limit: Optional[int]

    user_location: Optional[UserLocationParam]

    sources: Optional[List[WebSearchSource]]

    max_keyword: Optional[int]
