# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal

from arkruntime._models import BaseModel

from .embedding_item import EmbeddingItem
from .embedding_usage import EmbeddingUsage


class EmbeddingResponse(BaseModel):
    id: str
    """
    A unique identifier for the embedding response.
    """
    object: Literal["list"]
    """
    The object type. Always `list`.
    """
    created: int
    """
    Unix timestamp (in seconds) of when the response was created.
    """
    model: str
    """
    The model that produced the embeddings.
    """
    data: List[EmbeddingItem]
    """
    The list of embeddings, one per input.
    """
    usage: EmbeddingUsage
    """
    Token usage information for the request.
    """
