# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Union

from typing_extensions import TypeAliasType

Embedding = TypeAliasType("Embedding", Union[List[float], str])
"""
An embedding vector returned by the API. The shape depends on the
request's `encoding_format`: a list of floats when `float`, or a
base64-encoded string when `base64`.
"""
