# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Union

from typing_extensions import TypeAliasType

EmbeddingInput = TypeAliasType("EmbeddingInput", Union[str, List[str]])
"""
Input text(s) to embed. A single string embeds one input; an array of
strings embeds each element independently. Each string is limited to
100,000 bytes and arrays to 256 items.
"""
