# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import Required, TypedDict

from .embedding_input_param import EmbeddingInputParam
from .encoding_format import EncodingFormat


class EmbeddingRequestParam(TypedDict, total=False):
    model: Required[str]
    """Endpoint ID of the model to use."""

    input: Required[EmbeddingInputParam]
    """
    Input text to embed, as a string or array of strings. To embed
    multiple inputs in one request, pass an array.
    """

    encoding_format: Optional[EncodingFormat]
    """The format embeddings are returned in. Defaults to `float`."""

    dimensions: Optional[int]
    """Override the embedding dimensionality."""

    user: Optional[str]
    """
    A unique identifier representing the end-user, which can help the
    service monitor and detect abuse.
    """
