# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class EmbeddingUsage(BaseModel):
    """
    Token usage information for an embedding request.
    """

    prompt_tokens: int
    """
    The number of tokens consumed by the prompt.
    """
    total_tokens: int
    """
    The total number of tokens used by the request.
    """
