# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .embedding_input import EmbeddingInput
from .encoding_format import EncodingFormat


class EmbeddingRequest(BaseModel):
    model: str
    """
    Endpoint ID of the model to use.
    """
    input: EmbeddingInput
    """
    Input text to embed, as a string or array of strings. To embed
    multiple inputs in one request, pass an array.
    """
    encoding_format: Optional[EncodingFormat] = None
    """
    The format embeddings are returned in. Defaults to `float`.
    """
    dimensions: Optional[int] = None
    """
    Override the embedding dimensionality.
    """
    user: Optional[str] = None
    """
    A unique identifier representing the end-user, which can help the
    service monitor and detect abuse.
    """
