# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .embedding import Embedding


class EmbeddingItem(BaseModel):
    """
    A single embedding produced for one input.
    """

    embedding: Embedding
    """
    The embedding vector.
    """
    index: int
    """
    The index of this embedding in the request `input` array.
    """
    object: Literal["embedding"]
    """
    The object type. Always `embedding`.
    """
