# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .messages_response_content_part_server_tool_use import (
    MessagesResponseContentPartServerToolUse,
)
from .messages_response_content_part_text import MessagesResponseContentPartText
from .messages_response_content_part_thinking import MessagesResponseContentPartThinking
from .messages_response_content_part_tool_use import MessagesResponseContentPartToolUse
from .messages_response_content_part_web_search_tool_result import (
    MessagesResponseContentPartWebSearchToolResult,
)

ContentBlockStartContentBlock = TypeAliasType(
    "ContentBlockStartContentBlock",
    Annotated[
        Union[
            MessagesResponseContentPartText,
            MessagesResponseContentPartThinking,
            MessagesResponseContentPartToolUse,
            MessagesResponseContentPartServerToolUse,
            MessagesResponseContentPartWebSearchToolResult,
        ],
        Field(discriminator="type"),
    ],
)
