# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .content_block_start_content_block_server_tool_use import (
    ContentBlockStartContentBlockServerToolUse,
)
from .content_block_start_content_block_text import ContentBlockStartContentBlockText
from .content_block_start_content_block_thinking import (
    ContentBlockStartContentBlockThinking,
)
from .content_block_start_content_block_tool_use import (
    ContentBlockStartContentBlockToolUse,
)
from .content_block_start_content_block_web_search_tool_result import (
    ContentBlockStartContentBlockWebSearchToolResult,
)

ContentBlockStartContentBlock = TypeAliasType(
    "ContentBlockStartContentBlock",
    Annotated[
        Union[
            ContentBlockStartContentBlockText,
            ContentBlockStartContentBlockThinking,
            ContentBlockStartContentBlockToolUse,
            ContentBlockStartContentBlockServerToolUse,
            ContentBlockStartContentBlockWebSearchToolResult,
        ],
        Field(discriminator="type"),
    ],
)
