# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .content_block_start import ContentBlockStart
from .messages_error_response import MessagesErrorResponse
from .messages_response_content_block import MessagesResponseContentBlock
from .messages_response_content_block_stop import MessagesResponseContentBlockStop
from .messages_response_stream_message_delta import MessagesResponseStreamMessageDelta
from .messages_response_stream_message_start import MessagesResponseStreamMessageStart
from .messages_response_stream_message_stop import MessagesResponseStreamMessageStop

MessagesStreamEvent = TypeAliasType(
    "MessagesStreamEvent",
    Annotated[
        Union[
            MessagesResponseStreamMessageStart,
            ContentBlockStart,
            MessagesResponseContentBlock,
            MessagesResponseContentBlockStop,
            MessagesResponseStreamMessageDelta,
            MessagesResponseStreamMessageStop,
            MessagesErrorResponse,
        ],
        Field(discriminator="type"),
    ],
)
