# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal

from typing_extensions import Annotated

from arkruntime._models import BaseModel
from pydantic import Field


class MessagesContentPartServerToolUse(BaseModel):
    """
    Replays a server-managed tool invocation in an assistant message.
    """

    type: Literal["server_tool_use"]
    """
    The type of the content part. Always `server_tool_use`.
    """
    id: Annotated[str, Field(min_length=1)]
    """
    The non-empty public id of the server-managed tool invocation.
    """
    name: str
    """
    The name of the invoked server-managed tool.
    """
    input: Dict[str, object]
    """
    The input generated for the tool.
    """
