# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .messages_content_part_document_source_base64 import (
    MessagesContentPartDocumentSourceBase64,
)
from .messages_content_part_document_source_content import (
    MessagesContentPartDocumentSourceContent,
)
from .messages_content_part_document_source_text import (
    MessagesContentPartDocumentSourceText,
)
from .messages_content_part_document_source_url import (
    MessagesContentPartDocumentSourceUrl,
)

MessagesContentPartDocumentSource = TypeAliasType(
    "MessagesContentPartDocumentSource",
    Annotated[
        Union[
            MessagesContentPartDocumentSourceBase64,
            MessagesContentPartDocumentSourceText,
            MessagesContentPartDocumentSourceUrl,
            MessagesContentPartDocumentSourceContent,
        ],
        Field(discriminator="type"),
    ],
)
