# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Union

from typing_extensions import TypeAliasType

from .messages_document_content_text import MessagesDocumentContentText

MessagesDocumentContent = TypeAliasType(
    "MessagesDocumentContent", Union[MessagesDocumentContentText, Dict[str, object]]
)
"""
Inline document content must be a non-empty string or array.
"""
