# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .messages_response_stream_message_delta_delta import (
    MessagesResponseStreamMessageDeltaDelta,
)
from .messages_usage import MessagesUsage


class MessagesResponseStreamMessageDelta(BaseModel):
    type: Literal["message_delta"]
    delta: MessagesResponseStreamMessageDeltaDelta
    usage: Optional[MessagesUsage]
