# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .messages_response_content_block_delta_signature import (
    MessagesResponseContentBlockDeltaSignature,
)
from .messages_response_content_block_delta_text import (
    MessagesResponseContentBlockDeltaText,
)
from .messages_response_content_block_delta_thinking import (
    MessagesResponseContentBlockDeltaThinking,
)
from .messages_response_content_block_delta_tool_use import (
    MessagesResponseContentBlockDeltaToolUse,
)

MessagesResponseContentBlockDelta = TypeAliasType(
    "MessagesResponseContentBlockDelta",
    Annotated[
        Union[
            MessagesResponseContentBlockDeltaText,
            MessagesResponseContentBlockDeltaThinking,
            MessagesResponseContentBlockDeltaSignature,
            MessagesResponseContentBlockDeltaToolUse,
        ],
        Field(discriminator="type"),
    ],
)
