# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .messages_context_management_clear_tool_uses_trigger import (
    MessagesContextManagementClearToolUsesTrigger,
)
from .messages_context_management_keep import MessagesContextManagementKeep


class MessagesContextManagementClearToolUses(BaseModel):
    type: Literal["clear_tool_uses"]
    keep: Optional[MessagesContextManagementKeep] = None
    exclude_tools: Optional[List[str]] = None
    clear_tool_inputs: Optional[bool] = None
    trigger: Optional[MessagesContextManagementClearToolUsesTrigger] = None
