# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .messages_context_management_clear_thinking import (
    MessagesContextManagementClearThinking,
)
from .messages_context_management_clear_tool_uses import (
    MessagesContextManagementClearToolUses,
)

MessagesContextManagementEdit = TypeAliasType(
    "MessagesContextManagementEdit",
    Annotated[
        Union[
            MessagesContextManagementClearThinking,
            MessagesContextManagementClearToolUses,
        ],
        Field(discriminator="type"),
    ],
)
