# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .messages_response_stop_reason import MessagesResponseStopReason
from .messages_service_status import MessagesServiceStatus
from .messages_usage import MessagesUsage


class MessagesResponseStreamMessageStartMessage(BaseModel):
    type: Literal["message"]
    id: str
    role: Literal["assistant"]
    content: List[object]
    model: str
    service_status: Optional[MessagesServiceStatus] = None
    stop_reason: Optional[MessagesResponseStopReason]
    stop_sequence: Optional[str]
    usage: Optional[MessagesUsage]
