# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .messages_image_source_type import MessagesImageSourceType


class MessagesContentPartImageSource(BaseModel):
    type: MessagesImageSourceType
    """
    How the image is supplied.
    """
    url: Optional[str] = None
    """
    A URL of the image when `type` is `url`.
    """
    media_type: Optional[str] = None
    """
    The media type of base64-encoded image data.
    """
    data: Optional[str] = None
    """
    Base64-encoded image data when `type` is `base64`.
    """
    file_id: Optional[str] = None
    """
    The blob id of an image uploaded out-of-band.
    """
    is_frame: Optional[bool] = None
    """
    Whether this image was extracted from a document or video.
    """
