# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from typing_extensions import Annotated

from arkruntime._models import BaseModel
from pydantic import Field


class MessagesContentPartDocumentSourceText(BaseModel):
    type: Literal["text"]
    data: Annotated[str, Field(min_length=1)]
    """
    Plain-text document data.
    """
