# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .messages_message_content import MessagesMessageContent
from .messages_role import MessagesRole


class MessagesRequestMessage(BaseModel):
    role: MessagesRole
    """
    The role of the message author.
    """
    content: MessagesMessageContent
    """
    The contents of the message.
    """
