# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel

from .messages_response_content_block_delta import MessagesResponseContentBlockDelta


class MessagesResponseContentBlock(BaseModel):
    type: Literal["content_block_delta"]
    index: int
    delta: MessagesResponseContentBlockDelta
