# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal, Optional

from arkruntime._models import BaseModel

from .messages_response_content_part import MessagesResponseContentPart
from .messages_response_stop_reason import MessagesResponseStopReason
from .messages_service_status import MessagesServiceStatus
from .messages_usage import MessagesUsage


class MessagesResponse(BaseModel):
    """
    A Messages API response.
    """

    id: str
    """
    A unique identifier for the response.
    """
    type: Literal["message"]
    """
    The response object type. Always `message`.
    """
    role: Literal["assistant"]
    """
    The response role. Always `assistant`.
    """
    model: str
    """
    The model used to generate the response.
    """
    service_status: Optional[MessagesServiceStatus] = None
    """
    Service status such as model fallback information.
    """
    content: List[MessagesResponseContentPart]
    """
    Content generated by the model.
    """
    stop_reason: Optional[MessagesResponseStopReason] = None
    """
    The reason the model stopped generating tokens.
    """
    stop_sequence: Optional[str] = None
    """
    The custom stop sequence that was generated, if any.
    """
    usage: Optional[MessagesUsage] = None
    """
    Usage statistics for this request.
    """
