# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class MessagesContentPartThinking(BaseModel):
    type: Literal["thinking"]
    """
    The type of the content part. Always `thinking`.
    """
    thinking: Optional[str] = None
    """
    The model's thinking content.
    """
    signature: Optional[str] = None
    """
    An opaque signature used to replay thinking content.
    """
