# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .messages_message_content import MessagesMessageContent
from .messages_role import MessagesRole


class MessagesRequestMessage(BaseModel):
    role: MessagesRole
    """
    object non-empty role. Roles other than `user` and `assistant` are
    interpreted as system messages.
    """
    content: Optional[MessagesMessageContent] = None
    """
    The message content. For user and assistant messages, missing, null,
    and empty-array content is normalized to an empty string. For all other
    roles, the server requires this field to be present (null is accepted).
    This conditional requirement is validated by the server.
    """
