# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .messages_content_part_document import MessagesContentPartDocument
from .messages_content_part_image import MessagesContentPartImage
from .messages_content_part_server_tool_use import MessagesContentPartServerToolUse
from .messages_content_part_text import MessagesContentPartText
from .messages_content_part_thinking import MessagesContentPartThinking
from .messages_content_part_tool_result import MessagesContentPartToolResult
from .messages_content_part_tool_use import MessagesContentPartToolUse
from .messages_content_part_web_search_tool_result import (
    MessagesContentPartWebSearchToolResult,
)

MessagesContentPart = TypeAliasType(
    "MessagesContentPart",
    Annotated[
        Union[
            MessagesContentPartText,
            MessagesContentPartThinking,
            MessagesContentPartImage,
            MessagesContentPartDocument,
            MessagesContentPartToolUse,
            MessagesContentPartToolResult,
            MessagesContentPartServerToolUse,
            MessagesContentPartWebSearchToolResult,
        ],
        Field(discriminator="type"),
    ],
)
