# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Dict, Optional

from arkruntime._models import BaseModel
from pydantic import Field

from .messages_output_format_type import MessagesOutputFormatType


class MessagesOutputFormat(BaseModel):
    type: MessagesOutputFormatType
    """
    The requested output format.
    """
    schema_: Annotated[Optional[Dict[str, object]], Field(alias="schema")] = None
    """
    JSON Schema used when `type` is `json_schema`.
    """
