# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .messages_iteration_usage import MessagesIterationUsage
from .messages_server_tool_usage import MessagesServerToolUsage


class MessagesUsage(BaseModel):
    """
    Usage statistics for the Messages API.
    """

    input_tokens: Optional[int] = None
    """
    Number of prompt tokens excluding tokens read from the prefill cache.
    """
    output_tokens: Optional[int] = None
    """
    Number of tokens in the generated completion.
    """
    cache_creation_input_tokens: int
    """
    Cache-creation tokens are not currently supported; this field is returned as zero.
    """
    cache_read_input_tokens: Optional[int] = None
    """
    Number of prompt tokens read from the prefill cache.
    """
    server_tool_use: Optional[MessagesServerToolUsage] = None
    """
    Counts of requests dispatched by server-managed tools.
    """
    iterations: Optional[List[MessagesIterationUsage]] = None
    """
    One token-usage record per model iteration, included for multi-round requests.
    """
