# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Union

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

from .messages_context_management_keep_all import MessagesContextManagementKeepAll
from .messages_context_management_keep_thinking_turns import (
    MessagesContextManagementKeepThinkingTurns,
)
from .messages_context_management_keep_tool_uses import (
    MessagesContextManagementKeepToolUses,
)

MessagesContextManagementKeepParameter = TypeAliasType(
    "MessagesContextManagementKeepParameter",
    Annotated[
        Union[
            MessagesContextManagementKeepAll,
            MessagesContextManagementKeepThinkingTurns,
            MessagesContextManagementKeepToolUses,
        ],
        Field(discriminator="type"),
    ],
)
"""
What context to retain while applying a context-management edit.
"""
