# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Union

from typing_extensions import TypeAliasType

from .messages_context_management_keep_parameter import (
    MessagesContextManagementKeepParameter,
)

MessagesContextManagementKeep = TypeAliasType(
    "MessagesContextManagementKeep",
    Union[Literal["all"], MessagesContextManagementKeepParameter],
)
"""
A literal retention mode or a typed retention parameter.
"""
