# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from typing_extensions import Annotated

from arkruntime._models import BaseModel
from pydantic import Field

from .messages_max_uses import MessagesMaxUses
from .messages_tool_user_location import MessagesToolUserLocation


class MessagesTool(BaseModel):
    description: Optional[str] = None
    """
    A description of what the tool does and when the model should use it.
    """
    name: Annotated[str, Field(min_length=1)]
    """
    The tool name.
    """
    input_schema: Optional[Dict[str, object]] = None
    """
    The tool input, described as a JSON Schema object.
    """
    strict: Optional[bool] = None
    """
    Whether strict schema adherence is enabled for this tool.
    """
    type: Optional[str] = None
    """
    A tool type. A non-empty type without a description denotes a server-managed
    tool; web search uses the name `web_search` and a `web_search_` type prefix.
    """
    max_uses: Optional[MessagesMaxUses] = None
    """
    Maximum number of times a server-managed tool may be dispatched.
    """
    allowed_domains: Optional[List[str]] = None
    """
    Allowed domains. Cannot be non-empty together with `blocked_domains`.
    """
    blocked_domains: Optional[List[str]] = None
    """
    Blocked domains. Cannot be non-empty together with `allowed_domains`.
    """
    user_location: Optional[MessagesToolUserLocation] = None
    """
    Optional user location supplied to a server-managed web tool.
    """
