# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class MessagesServerToolUsage(BaseModel):
    web_search_requests: int
    """
    Number of web-search requests dispatched by server-managed tools.
    """
    web_fetch_requests: int
    """
    Number of web-fetch requests dispatched by server-managed tools.
    """
