# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Union

from typing_extensions import TypeAliasType

from .messages_content_part import MessagesContentPart

MessagesMessageContent = TypeAliasType(
    "MessagesMessageContent", Union[str, List[MessagesContentPart]]
)
"""
Message content can be a bare string or an array of typed content parts.
"""
