# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from typing_extensions import Annotated

from arkruntime._models import BaseModel
from pydantic import Field


class MessagesOutputFormatJsonObject(BaseModel):
    type: Literal["json_object"]
    schema_: Annotated[Optional[object], Field(alias="schema")] = None
