# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, Literal

from arkruntime._models import BaseModel


class MessagesContentPartToolUse(BaseModel):
    type: Literal["tool_use"]
    """
    The type of the content part. Always `tool_use`.
    """
    id: str
    """
    The id of the tool invocation.
    """
    name: str
    """
    The name of the invoked tool.
    """
    input: Dict[str, object]
    """
    The input generated for the tool.
    """
