# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional, Union

from typing_extensions import TypeAliasType

MessagesStopSequences = TypeAliasType(
    "MessagesStopSequences", Optional[Union[str, List[str]]]
)
"""
One stop sequence or an array of stop sequences. The count limit is
model-dependent (default four); null is treated as an empty list.
"""
