# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel


class MessagesIterationUsage(BaseModel):
    type: str
    """
    The iteration usage record type.
    """
    input_tokens: int
    """
    Number of input tokens consumed by this model iteration.
    """
    output_tokens: int
    """
    Number of output tokens generated by this model iteration.
    """
    cache_read_input_tokens: int
    """
    Number of cached input tokens read by this model iteration.
    """
