# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from arkruntime._models import BaseModel

from .messages_tool_user_location import MessagesToolUserLocation


class MessagesTool(BaseModel):
    description: Optional[str] = None
    """
    A description of what the tool does and when the model should use it.
    """
    name: str
    """
    The tool name.
    """
    input_schema: Optional[Dict[str, object]] = None
    """
    The tool input, described as a JSON Schema object.
    """
    strict: Optional[bool] = None
    """
    Whether strict schema adherence is enabled for this tool.
    """
    type: Optional[str] = None
    """
    A server-managed tool version, such as `web_search_20250305`.
    """
    max_uses: Optional[int] = None
    """
    Maximum number of times a server-managed tool may be dispatched.
    """
    allowed_domains: Optional[List[str]] = None
    """
    Domains that a server-managed web tool is allowed to access.
    """
    blocked_domains: Optional[List[str]] = None
    """
    Domains that a server-managed web tool must not access.
    """
    user_location: Optional[MessagesToolUserLocation] = None
    """
    Optional user location supplied to a server-managed web tool.
    """
