# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class MessagesResponseContentPartThinking(BaseModel):
    type: Literal["thinking"]
    thinking: str
    signature: Optional[str] = None
