# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

MessagesRole = TypeAliasType("MessagesRole", Annotated[str, Field(min_length=1)])
"""
object non-empty role is accepted; roles other than `user` and `assistant`
are interpreted as `system`.
"""
