# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from arkruntime._models import BaseModel

from .messages_context_management import MessagesContextManagement
from .messages_metadata import MessagesMetadata
from .messages_output_config import MessagesOutputConfig
from .messages_output_format import MessagesOutputFormat
from .messages_request_message import MessagesRequestMessage
from .messages_request_service_tier import MessagesRequestServiceTier
from .messages_stop_sequences import MessagesStopSequences
from .messages_stream_options import MessagesStreamOptions
from .messages_system import MessagesSystem
from .messages_thinking import MessagesThinking
from .messages_tool import MessagesTool
from .messages_tool_choice import MessagesToolChoice


class MessagesRequest(BaseModel):
    """
    Creates a model response for the supplied conversation.
    """

    messages: List[MessagesRequestMessage]
    """
    A list of messages comprising the conversation so far.
    """
    model: str
    """
    Endpoint ID of the model to use.
    """
    system: Optional[MessagesSystem] = None
    """
    A system prompt supplied separately from the conversation messages.
    """
    frequency_penalty: Optional[float] = None
    """
    Number between -2.0 and 2.0. Positive values penalize tokens based on
    their existing frequency in the generated text.
    """
    logit_bias: Optional[Dict[str, float]] = None
    """
    Modify the likelihood of token IDs appearing in the response. Values
    range from -100 to 100.
    """
    logprobs: Optional[bool] = None
    """
    Whether to return log probabilities of output tokens.
    """
    max_tokens: Optional[int] = None
    """
    Maximum number of tokens that may be generated.
    """
    presence_penalty: Optional[float] = None
    """
    Number between -2.0 and 2.0. Positive values penalize tokens based on
    whether they have appeared in the generated text.
    """
    repetition_penalty: Optional[float] = None
    """
    Number between 0.0 and 2.0 that penalizes repetition.
    """
    output_format: Optional[MessagesOutputFormat] = None
    """
    The format the model must produce.
    """
    stop_sequences: Optional[MessagesStopSequences] = None
    """
    Sequences that stop generation when produced.
    """
    stream: Optional[bool] = None
    """
    Whether to stream the response as server-sent events.
    """
    stream_options: Optional[MessagesStreamOptions] = None
    """
    Options for streaming responses.
    """
    temperature: Optional[float] = None
    """
    Sampling temperature between 0 and 2.
    """
    tool_choice: Optional[MessagesToolChoice] = None
    """
    Controls which tool, if any, the model calls.
    """
    tools: Optional[List[MessagesTool]] = None
    """
    Tools the model may call.
    """
    top_logprobs: Optional[int] = None
    """
    Number of most-likely tokens returned at each position. Range 0-20.
    """
    top_p: Optional[float] = None
    """
    Nucleus sampling probability between 0 and 1.
    """
    service_tier: Optional[MessagesRequestServiceTier] = None
    """
    Latency tier used to process the request.
    """
    thinking: Optional[MessagesThinking] = None
    """
    Thinking-mode configuration.
    """
    output_config: Optional[MessagesOutputConfig] = None
    """
    Output configuration for reasoning models.
    """
    metadata: Optional[MessagesMetadata] = None
    """
    Metadata associated with the request.
    """
    context_management: Optional[MessagesContextManagement] = None
    """
    Context-editing rules applied before inference.
    """
