# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .messages_tool_choice_any import MessagesToolChoiceAny
from .messages_tool_choice_auto import MessagesToolChoiceAuto
from .messages_tool_choice_none import MessagesToolChoiceNone
from .messages_tool_choice_tool import MessagesToolChoiceTool

MessagesToolChoice = TypeAliasType(
    "MessagesToolChoice",
    Annotated[
        Union[
            MessagesToolChoiceAuto,
            MessagesToolChoiceAny,
            MessagesToolChoiceNone,
            MessagesToolChoiceTool,
        ],
        Field(discriminator="type"),
    ],
)
