# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pydantic import Field
from typing_extensions import Annotated, TypeAliasType

Description = TypeAliasType("Description", Annotated[str, Field(max_length=500)])
"""
A user-provided file description, limited to 500 characters.
"""
