# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .preprocess_configs import PreprocessConfigs
from .purpose import Purpose
from .tos_storage import TosStorage


class FileCreateRequest(BaseModel):
    purpose: Purpose
    """
    The intended purpose of the uploaded file.
    """
    preprocess_configs: Optional[PreprocessConfigs] = None
    """
    Preprocessing configuration to apply at upload time.
    """
    expire_at: Optional[int] = None
    """
    Unix timestamp (seconds) after which the file should be purged.
    Defaults to 7 days from upload when omitted.
    """
    url: Optional[str] = None
    """
    Alternative file source. Accepts http/https or `tos://` schemes.
    Mutually exclusive with the binary `file` part.
    """
    tos: Optional[TosStorage] = None
    """
    User-owned TOS bucket destination. Required when `url` is provided;
    optional with binary upload.
    """
