# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel

from .file_error import FileError
from .preprocess_configs import PreprocessConfigs
from .purpose import Purpose
from .status import Status


class FileObject(BaseModel):
    """
    File metadata returned by upload, retrieve, and list operations.
    """

    object: Literal["file"]
    """
    The object type. Always `file`.
    """
    id: str
    """
    Server-generated file id.
    """
    purpose: Purpose
    """
    The intended purpose of the uploaded file.
    """
    filename: str
    """
    Original filename of the uploaded file.
    """
    bytes: Optional[int] = None
    """
    Size of the file in bytes.
    """
    mime_type: Optional[str] = None
    """
    Detected or declared MIME type of the file.
    """
    created_at: int
    """
    Unix timestamp (seconds) when the file was created.
    """
    expire_at: int
    """
    Unix timestamp (seconds) after which the file is purged.
    """
    status: Status
    """
    Lifecycle status of the file.
    """
    download_url: Optional[str] = None
    """
    Pre-signed download URL pointing at the underlying TOS object.
    """
    error: Optional[FileError] = None
    """
    Failure details. Only set when `status` is `failed`.
    """
    preprocess_configs: Optional[PreprocessConfigs] = None
    """
    Preprocessing configuration applied at upload time.
    """
