# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from arkruntime._models import BaseModel


class FileDeleted(BaseModel):
    """
    Response for a successful file deletion.
    """

    object: Literal["file"]
    """
    The object type. Always `file`.
    """
    id: str
    """
    Id of the deleted file.
    """
    deleted: bool
    """
    True when the deletion succeeded.
    """
