# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal

from arkruntime._models import BaseModel

from .file_object import FileObject


class FileListResponse(BaseModel):
    """
    Cursor-paginated response for `GET /files`.
    """

    object: Literal["file"]
    """
    The object type. The Ark file list endpoint returns `file` here
    (a non-standard convention) rather than `list`. Kept as the literal the
    server actually emits so generated enums in all SDKs decode cleanly.
    """
    data: List[FileObject]
    """
    The list of file objects on this page.
    """
    first_id: str
    """
    Id of the first item in `data`, useful for prepending pages.
    """
    last_id: str
    """
    Id of the last item in `data`, useful as the `after` cursor.
    """
    has_more: bool
    """
    True when more items are available after `last_id`.
    """
