# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class Status(str, Enum):
    """
    Lifecycle status of a file in the storage backend.
    """

    active = "active"
    processing = "processing"
    failed = "failed"
