# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict


class TosStorageParam(TypedDict, total=False):
    """
    User-owned TOS bucket destination. When provided, files are stored in
    the user's bucket instead of the default storage and do not count
    against the 20GB free quota.
    """

    bucket: Optional[str]
    """TOS bucket name."""

    prefix: Optional[str]
    """Optional key prefix inside the bucket."""
