# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import TypedDict


class VideoParam(TypedDict, total=False):
    """
    Video preprocessing configuration.
    """

    fps: Optional[float]
    """Frames-per-second sampling target for video preprocessing."""

    model: Optional[str]
    """Optional video preprocessing model identifier."""
