# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal

from arkruntime._models import BaseModel


class TokenizationItem(BaseModel):
    """
    A single tokenization result for one input string.
    """

    index: int
    """
    The index of this result in the request `text` array.
    """
    object: Literal["tokenization"]
    """
    The object type. Always `tokenization`.
    """
    total_tokens: int
    """
    The total number of tokens produced for this input.
    """
    token_ids: List[int]
    """
    The token IDs produced by the tokenizer, in order.
    """
    offset_mapping: List[List[int]]
    """
    Per-token character offsets into the input string, as
    `[start, end]` pairs aligned with `token_ids`.
    """
