# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import Required, TypedDict

from .tokenization_input_param import TokenizationInputParam


class TokenizationRequestParam(TypedDict, total=False):
    model: Required[str]
    """Endpoint ID or model name to tokenize for."""

    text: Required[TokenizationInputParam]
    """
    Input text to tokenize, as a string or array of strings. To tokenize
    multiple inputs in one request, pass an array.
    """

    user: Optional[str]
    """
    A unique identifier representing the end-user. Currently accepted but
    not used by the server; reserved for parity with other endpoints.
    """
