# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Literal

from arkruntime._models import BaseModel

from .tokenization_item import TokenizationItem


class TokenizationResponse(BaseModel):
    id: str
    """
    A unique identifier for the tokenization response.
    """
    object: Literal["list"]
    """
    The object type. Always `list`.
    """
    created: int
    """
    Unix timestamp (in seconds) of when the response was created.
    """
    model: str
    """
    The model that produced the tokenization.
    """
    data: List[TokenizationItem]
    """
    The list of tokenization results, one per input.
    """
