# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Union

from typing_extensions import TypeAliasType

TokenizationInput = TypeAliasType("TokenizationInput", Union[str, List[str]])
"""
Input text(s) to tokenize. A single string tokenizes one input; an array
of strings tokenizes each element independently.
"""
