# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from .create_skill_request import CreateSkillRequest
from .skill import Skill

__all__ = [
    "CreateSkillRequest",
    "Skill",
]

# Hand-written extras (preserved across regen via Makefile rsync --exclude=*_shim.py).
from ._init_extras_shim import *  # noqa: F401,F403
