# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class SkillVersion(BaseModel):
    """
    Skill 版本摘要。

    CreateSkillVersion / ListSkillVersions / GetSkillVersion 返回该对象；主
    Skill 的 latest_version 会由服务端在新版本创建成功后推进。
    """

    id: str
    """
    SkillVersion ID，形如 `skillver-...`。
    """
    type: Literal["skill_version"]
    """
    固定 `"skill_version"`。
    """
    skill_id: str
    """
    归属 Skill ID。
    """
    version: str
    """
    版本号，服务端按字符串形式自增，例如 `"1"`、`"2"`。
    """
    display_title: str
    """
    该版本的展示名。
    """
    description: Optional[str] = None
    """
    该版本的描述信息。
    """
    created_at: str
    """
    创建时间，RFC 3339 UTC 秒级精度。
    """
