# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, Optional

from arkruntime._models import BaseModel


class Skill(BaseModel):
    """
    用户上传到 Managed Agents 控制面的技能摘要。

    与其他资源不同：Skill 用 `object` 而不是 `type` 作为对象类型判别字段，
    且 `created_at` 是 Unix 秒（int64）而非 RFC 3339 字符串 —— 与
    ark-managed-agents thrift 契约保持一致。
    """

    id: str
    """
    Skill ID，形如 `skill_01XJ5...`。
    """
    object: Literal["skill"]
    """
    固定 `"skill"`。
    """
    created_at: int
    """
    创建时间（Unix 秒）。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    latest_version: str
    """
    最新版本号。
    """
    name: str
    """
    人类可读名称。
    """
