# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Literal, Optional

from arkruntime._models import BaseModel

from .agent_skill_ref import AgentSkillRef
from .mcp_server import MCPServer
from .model_config import ModelConfig
from .multiagent_config import MultiagentConfig
from .tag import Tag
from .tool_item import ToolItem


class Agent(BaseModel):
    """
    ARK Managed Agents 控制面核心资源
    （模型 + System Prompt + Tools + MCP servers + Skills 的可复用、版本化配置）。
    """

    id: str
    """
    Agent ID，格式 `agent_<opaque>`。对外暴露给 session 引用。
    """
    type: Literal["agent"]
    """
    固定 `"agent"`。
    """
    name: str
    """
    人类可读名称，1–256 字符。
    """
    description: Optional[str] = None
    """
    描述信息，最大 2048 字符。
    """
    version: int
    """
    版本号；每次 update 递增。
    """
    model: Optional[ModelConfig] = None
    """
    模型配置。
    """
    system: Optional[str] = None
    """
    System prompt，最大 100,000 字符。
    """
    tools: Optional[List[ToolItem]] = None
    """
    工具配置数组。
    """
    mcp_servers: Optional[List[MCPServer]] = None
    """
    MCP 服务器列表，最多 20 项。
    """
    skills: Optional[List[AgentSkillRef]] = None
    """
    Skill 列表，最多 20 项。
    """
    multiagent: Optional[MultiagentConfig] = None
    """
    多 Agent 编排拓扑（可选）。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据。最多 16 对，key ≤ 64 字符，value ≤ 512 字符。
    """
    tags: Optional[List[Tag]] = None
    """
    资源标签。
    """
    created_at: str
    """
    RFC 3339 时间。
    """
    updated_at: str
    """
    RFC 3339 时间。
    """
