# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .agent_ref_type import AgentRefType
from .agent_skill_ref import AgentSkillRef
from .mcp_server import MCPServer
from .model_config import ModelConfig
from .tool_item import ToolItem


class AgentRef(BaseModel):
    """
    coordinator Agent 编排的下属 Agent 引用。
    """

    type: AgentRefType
    """
    引用类型。
    """
    id: Optional[str] = None
    """
    被引用 Agent 的 ID。
    """
    version: Optional[int] = None
    """
    被引用 Agent 的版本号。
    """
    name: Optional[str] = None
    """
    Session 响应中冻结的成员 Agent 名称。
    """
    description: Optional[str] = None
    """
    Session 响应中冻结的成员 Agent 描述。
    """
    model: Optional[ModelConfig] = None
    """
    Session 响应中冻结的成员 Agent 模型配置。
    """
    system: Optional[str] = None
    """
    Session 响应中冻结的成员 Agent system prompt。
    """
    tools: Optional[List[ToolItem]] = None
    """
    Session 响应中冻结的成员 Agent 工具配置。
    """
    mcp_servers: Optional[List[MCPServer]] = None
    """
    Session 响应中冻结的成员 Agent MCP servers。
    """
    skills: Optional[List[AgentSkillRef]] = None
    """
    Session 响应中冻结的成员 Agent skills。
    """
    display_name: Optional[str] = None
    """
    Session 响应中冻结的成员 Agent 展示名。
    """
