# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .skill_ref_type import SkillRefType


class AgentSkillRef(BaseModel):
    """
    Agent 引用的一条 Skill。
    """

    type: SkillRefType
    """
    Skill 引用类型。一期仅支持 `skill_hub`。
    """
    skill_id: Optional[str] = None
    """
    Skill ID，形如 `skill_01XJ5...`。
    """
    version: Optional[str] = None
    """
    Skill 版本号，可选；不传走最新。
    """
