# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from arkruntime._models import BaseModel

from .agent_skill_ref import AgentSkillRef
from .mcp_server import MCPServer
from .model_config import ModelConfig
from .multiagent_config import MultiagentConfig
from .tag import Tag
from .tool_item import ToolItem


class CreateAgentRequest(BaseModel):
    """
    创建 Agent 的请求体。
    """

    name: str
    """
    人类可读名称。
    """
    model: ModelConfig
    """
    模型配置。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    system: Optional[str] = None
    """
    System prompt。
    """
    mcp_servers: Optional[List[MCPServer]] = None
    """
    MCP 服务器列表。
    """
    tools: Optional[List[ToolItem]] = None
    """
    工具配置数组。
    """
    skills: Optional[List[AgentSkillRef]] = None
    """
    Skill 引用列表。
    """
    multiagent: Optional[MultiagentConfig] = None
    """
    多 Agent 编排拓扑。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据。
    """
    tags: Optional[List[Tag]] = None
    """
    资源标签。
    """
