# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from arkruntime._models import BaseModel


class CustomToolInputSchema(BaseModel):
    """
    Custom tool 的输入 JSON Schema。
    """

    type: Optional[str] = None
    """
    JSON Schema 顶层类型；缺省按 `"object"` 处理。
    """
    properties: Optional[Dict[str, object]] = None
    """
    JSON Schema properties 对象。
    """
    required: Optional[List[str]] = None
    """
    必填属性名列表。
    """
