# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .agent import Agent


class ListAgentsResponse(BaseModel):
    """
    List Agents / List Agent Versions 响应体。
    """

    data: List[Agent]
    """
    本页 Agent 列表。
    """
    next_page: Optional[str] = None
    """
    下一页页码；无更多数据时为空字符串或缺省。
    """
    total: Optional[int] = None
    """
    命中总条数（可选，服务器决定是否返回）。
    """
