# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .mcp_server_type import MCPServerType


class MCPServer(BaseModel):
    """
    一个外接 MCP 服务器。
    """

    name: str
    """
    在本 Agent 内唯一，被 `tools[].mcp_server_name` 引用。
    """
    type: MCPServerType
    """
    MCP server 类型，当前固定 `"url"`。
    """
    url: str
    """
    MCP server URL。
    """
