# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .model_speed import ModelSpeed


class ModelConfig(BaseModel):
    """
    Agent 引用的模型配置。
    """

    id: str
    """
    模型 ID，例如 `claude-opus-4-7` / `claude-sonnet-4-6` / `claude-haiku-4-5`。
    """
    speed: Optional[ModelSpeed] = None
    """
    速度档位。空字符串走默认（并非所有模型都支持 `fast`）。
    """
