# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from arkruntime._models import BaseModel

from .permission_policy_type import PermissionPolicyType


class PermissionPolicy(BaseModel):
    """
    工具调用许可策略。
    """

    type: PermissionPolicyType
    """
    策略类型。
    """
