# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class Tag(BaseModel):
    """
    资源标签。key 必填，value 可空。
    """

    key: str
    """
    标签 key。
    """
    value: Optional[str] = None
    """
    标签 value；可空。
    """
