# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .permission_policy import PermissionPolicy


class ToolConfig(BaseModel):
    """
    toolset 类型工具的单条配置项。
    """

    name: str
    """
    工具名。
    """
    enabled: Optional[bool] = None
    """
    是否启用；缺省走 `default_config.enabled`。
    """
    permission_policy: Optional[PermissionPolicy] = None
    """
    许可策略；缺省走 `default_config.permission_policy`。
    """
