# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .tool_config import ToolConfig
from .tool_default_config import ToolDefaultConfig


class ToolItem(BaseModel):
    """
    一条工具配置。按 `type` 分三类：
    - `agent_toolset_<date>`：内置工具集（当前默认 `agent_toolset_20260701`；
    存量 `agent_toolset_20260401` 仍兼容）
    - `mcp_toolset`：来自 `mcp_servers[]` 的工具集
    - `custom`：客户端执行的自定义工具

    所有变体字段合并在一个 model 里，未使用的字段留空即可（proto oneof
    风格；wire 上就是同一个 JSON 对象按 `type` 决定语义）。
    """

    type: str
    """
    工具 type。
    """
    configs: Optional[List[ToolConfig]] = None
    """
    toolset 类专用。
    """
    default_config: Optional[ToolDefaultConfig] = None
    """
    toolset 类专用；未在 `configs` 里显式列出的工具走此默认。
    """
    mcp_server_name: Optional[str] = None
    """
    `mcp_toolset` 专用；须匹配 `mcp_servers[].name`。
    """
    name: Optional[str] = None
    """
    `custom` 专用；1–128 字符，`[A-Za-z0-9_-]`。
    """
    description: Optional[str] = None
    """
    `custom` 专用；1–1024 字符。
    """
    input_schema: Optional[str] = None
    """
    `custom` 专用；承载 JSON Schema 的字符串形态
    （wire 上是 JSON-encoded string，非 nested object）。
    """
