# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Dict, List, Optional

from arkruntime._models import BaseModel

from .agent_skill_ref import AgentSkillRef
from .mcp_server import MCPServer
from .model_config import ModelConfig
from .multiagent_config import MultiagentConfig
from .tool_item import ToolItem


class UpdateAgentRequest(BaseModel):
    """
    更新 Agent 的请求体。语义：
    - 省略 = 保留
    - 空字符串/null = 清空（仅 description / system / 数组类）
    - `name` / `model` 不可清空
    - `metadata` 走 patch
    - `mcp_servers` / `tools` / `skills` 整体替换
    - `version` 必填，必须等于服务端当前版本（乐观并发控制）
    """

    version: int
    """
    期望更新的当前版本号。用于乐观并发控制；不匹配时拒绝写入。
    """
    name: Optional[str] = None
    """
    人类可读名称。
    """
    model: Optional[ModelConfig] = None
    """
    模型配置。
    """
    description: Optional[str] = None
    """
    描述信息。
    """
    system: Optional[str] = None
    """
    System prompt。
    """
    mcp_servers: Optional[List[MCPServer]] = None
    """
    MCP 服务器列表（整体替换）。
    """
    tools: Optional[List[ToolItem]] = None
    """
    工具配置数组（整体替换）。
    """
    skills: Optional[List[AgentSkillRef]] = None
    """
    Skill 引用列表（整体替换）。
    """
    multiagent: Optional[MultiagentConfig] = None
    """
    多 Agent 编排拓扑。
    """
    metadata: Optional[Dict[str, str]] = None
    """
    用户自定义键值对元数据（patch）。
    """
