# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class ContentType(str, Enum):
    """
    Discriminator for an entry in the request `content` list.
    """

    text = "text"
    image_url = "image_url"
    video_url = "video_url"
    audio_url = "audio_url"
    draft_task = "draft_task"
