# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .reasoning_effort import ReasoningEffort
from .task_content import TaskContent
from .task_error import TaskError
from .task_status import TaskStatus
from .task_usage import TaskUsage
from .tool import Tool


class ContentGenerationTask(BaseModel):
    """
    Snapshot of a content-generation task.
    """

    id: str
    """
    Task identifier.
    """
    model: str
    """
    Model used to produce the result.
    """
    status: TaskStatus
    """
    Lifecycle state.
    """
    error: Optional[TaskError] = None
    """
    Populated when the task ended in `failed`.
    """
    content: Optional[TaskContent] = None
    """
    Generated artifact URLs. Populated when the task succeeded.
    """
    usage: Optional[TaskUsage] = None
    """
    Token / tool usage. Populated when the task is in a terminal state.
    """
    created_at: Optional[int] = None
    """
    Unix timestamp (seconds) when the task was created.
    """
    updated_at: Optional[int] = None
    """
    Unix timestamp (seconds) when the task last changed.
    """
    seed: Optional[int] = None
    """
    Random seed actually used by the algorithm.
    """
    resolution: Optional[str] = None
    """
    Resolution of the generated output.
    """
    ratio: Optional[str] = None
    """
    Aspect ratio of the generated output.
    """
    duration: Optional[int] = None
    """
    Duration of the generated output (seconds).
    """
    frames: Optional[int] = None
    """
    Frame count of the generated output.
    """
    framespersecond: Optional[int] = None
    """
    Frames-per-second of the generated output.
    """
    revised_prompt: Optional[str] = None
    """
    Server-side rewritten prompt, when prompt optimization ran.
    """
    subdivisionlevel: Optional[str] = None
    """
    Render-quality tier echoed back.
    """
    fileformat: Optional[str] = None
    """
    File format echoed back.
    """
    service_tier: Optional[str] = None
    """
    Service tier the task was scheduled on.
    """
    execution_expires_after: Optional[int] = None
    """
    Soft execution deadline echoed back.
    """
    generate_audio: Optional[bool] = None
    """
    Whether audio was generated.
    """
    draft: Optional[bool] = None
    """
    Whether this task is a draft.
    """
    draft_task_id: Optional[str] = None
    """
    When this task is a refinement, the upstream draft id.
    """
    tools: Optional[List[Tool]] = None
    """
    Tools that were enabled for the task.
    """
    reasoning_effort: Optional[ReasoningEffort] = None
    """
    Reasoning effort echoed back.
    """
    safety_identifier: Optional[str] = None
    """
    Safety identifier echoed back.
    """
