# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .audio_url import AudioURL
from .content_type import ContentType
from .draft_task import DraftTask
from .image_url import ImageURL
from .video_url import VideoURL


class ContentItem(BaseModel):
    """
    One element of a generation request `content` list. Exactly one of
    `text` / `image_url` / `video_url` / `audio_url` / `draft_task` must be
    set, matching the value of `type`.
    """

    type: ContentType
    """
    Discriminator for which payload field is set.
    """
    text: Optional[str] = None
    """
    Text content. Required when `type` is `text`.
    """
    image_url: Optional[ImageURL] = None
    """
    Image content. Required when `type` is `image_url`.
    """
    video_url: Optional[VideoURL] = None
    """
    Video content. Required when `type` is `video_url`.
    """
    audio_url: Optional[AudioURL] = None
    """
    Audio content. Required when `type` is `audio_url`.
    """
    draft_task: Optional[DraftTask] = None
    """
    Draft-task reference. Required when `type` is `draft_task`.
    """
    role: Optional[str] = None
    """
    Optional role tag (e.g. `first_frame`, `reference_image`).
    """
