# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from typing_extensions import Required, TypedDict

from .audio_url_param import AudioURLParam
from .content_type import ContentType
from .draft_task_param import DraftTaskParam
from .image_url_param import ImageURLParam
from .video_url_param import VideoURLParam


class ContentItemParam(TypedDict, total=False):
    """
    One element of a generation request `content` list. Exactly one of
    `text` / `image_url` / `video_url` / `audio_url` / `draft_task` must be
    set, matching the value of `type`.
    """

    type: Required[ContentType]
    """Discriminator for which payload field is set."""

    text: Optional[str]
    """Text content. Required when `type` is `text`."""

    image_url: Optional[ImageURLParam]
    """Image content. Required when `type` is `image_url`."""

    video_url: Optional[VideoURLParam]
    """Video content. Required when `type` is `video_url`."""

    audio_url: Optional[AudioURLParam]
    """Audio content. Required when `type` is `audio_url`."""

    draft_task: Optional[DraftTaskParam]
    """Draft-task reference. Required when `type` is `draft_task`."""

    role: Optional[str]
    """Optional role tag (e.g. `first_frame`, `reference_image`)."""
