# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from typing_extensions import Required, TypedDict

from .content_item_param import ContentItemParam
from .reasoning_effort import ReasoningEffort
from .tool_param import ToolParam


class CreateContentGenerationTaskRequestParam(TypedDict, total=False):
    model: Required[str]
    """The model identifier to use."""

    content: Required[List[ContentItemParam]]
    """Ordered list of content inputs (text / image / video / audio / draft)."""

    callback_url: Optional[str]
    """Webhook URL invoked when the task transitions to a terminal state."""

    return_last_frame: Optional[bool]
    """Whether to also return a still of the last generated frame."""

    service_tier: Optional[str]
    """Service tier hint (e.g. `default`, `priority`)."""

    execution_expires_after: Optional[int]
    """Soft execution deadline in seconds since task creation."""

    generate_audio: Optional[bool]
    """Generate audio alongside the video."""

    camera_fixed: Optional[bool]
    """Lock the camera; disables motion."""

    watermark: Optional[bool]
    """Embed a watermark in the generated video."""

    seed: Optional[int]
    """Random seed for reproducible generation."""

    resolution: Optional[str]
    """Output resolution (e.g. `720p`, `1080p`)."""

    ratio: Optional[str]
    """Output aspect ratio (e.g. `16:9`)."""

    duration: Optional[int]
    """Duration of the generated video in seconds."""

    frames: Optional[int]
    """Total number of frames (alternative to `duration`)."""

    subdivision_level: Optional[str]
    """Render-quality tier (e.g. `high`, `medium`, `low`)."""

    file_format: Optional[str]
    """Output file format (e.g. `mp4`, `glb`)."""

    draft: Optional[bool]
    """Mark this task as a draft (cheaper, lower-quality)."""

    optimize_prompt: Optional[bool]
    """Run the prompt-optimization pass before generation."""

    tools: Optional[List[ToolParam]]
    """Tools the model may invoke during generation."""

    reasoning_effort: Optional[ReasoningEffort]
    """Hint for how much reasoning the model should do."""

    human_face_mode: Optional[str]
    """Human-face handling mode (e.g. `strict`, `relaxed`)."""

    safety_identifier: Optional[str]
    """End-user identifier for safety/abuse signals."""
