# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List, Optional

from arkruntime._models import BaseModel

from .content_item import ContentItem
from .reasoning_effort import ReasoningEffort
from .tool import Tool


class CreateContentGenerationTaskRequest(BaseModel):
    model: str
    """
    The model identifier to use.
    """
    content: List[ContentItem]
    """
    Ordered list of content inputs (text / image / video / audio / draft).
    """
    callback_url: Optional[str] = None
    """
    Webhook URL invoked when the task transitions to a terminal state.
    """
    return_last_frame: Optional[bool] = None
    """
    Whether to also return a still of the last generated frame.
    """
    service_tier: Optional[str] = None
    """
    Service tier hint (e.g. `default`, `priority`).
    """
    execution_expires_after: Optional[int] = None
    """
    Soft execution deadline in seconds since task creation.
    """
    generate_audio: Optional[bool] = None
    """
    Generate audio alongside the video.
    """
    camera_fixed: Optional[bool] = None
    """
    Lock the camera; disables motion.
    """
    watermark: Optional[bool] = None
    """
    Embed a watermark in the generated video.
    """
    seed: Optional[int] = None
    """
    Random seed for reproducible generation.
    """
    resolution: Optional[str] = None
    """
    Output resolution (e.g. `720p`, `1080p`).
    """
    ratio: Optional[str] = None
    """
    Output aspect ratio (e.g. `16:9`).
    """
    duration: Optional[int] = None
    """
    Duration of the generated video in seconds.
    """
    frames: Optional[int] = None
    """
    Total number of frames (alternative to `duration`).
    """
    subdivision_level: Optional[str] = None
    """
    Render-quality tier (e.g. `high`, `medium`, `low`).
    """
    file_format: Optional[str] = None
    """
    Output file format (e.g. `mp4`, `glb`).
    """
    draft: Optional[bool] = None
    """
    Mark this task as a draft (cheaper, lower-quality).
    """
    optimize_prompt: Optional[bool] = None
    """
    Run the prompt-optimization pass before generation.
    """
    tools: Optional[List[Tool]] = None
    """
    Tools the model may invoke during generation.
    """
    reasoning_effort: Optional[ReasoningEffort] = None
    """
    Hint for how much reasoning the model should do.
    """
    human_face_mode: Optional[str] = None
    """
    Human-face handling mode (e.g. `strict`, `relaxed`).
    """
    safety_identifier: Optional[str] = None
    """
    End-user identifier for safety/abuse signals.
    """
