# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class ImageRole(str, Enum):
    """
    Role hint for an image content entry (first frame, last frame, etc).
    """

    first_frame = "first_frame"
    last_frame = "last_frame"
    reference_image = "reference_image"
    mask = "mask"
