# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from enum import Enum


class TaskStatus(str, Enum):
    """
    Lifecycle state of a content-generation task.
    """

    queued = "queued"
    running = "running"
    cancelled = "cancelled"
    succeeded = "succeeded"
    failed = "failed"
