# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel

from .tool_usage import ToolUsage


class TaskUsage(BaseModel):
    completion_tokens: int
    """
    Tokens consumed by the completion.
    """
    total_tokens: int
    """
    Total tokens consumed by the request.
    """
    tool_usage: Optional[ToolUsage] = None
    """
    Per-tool usage breakdown.
    """
