# Generated by datamodel-code-generator from ark-apis typespec/openapi.
# DO NOT EDIT — regenerate with `make gen-py-<api>` in ark-apis.
#
# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Optional

from arkruntime._models import BaseModel


class TaskContent(BaseModel):
    """
    Generated artifact references attached to a finished task.
    """

    video_url: Optional[str] = None
    """
    URL of the generated video.
    """
    file_url: Optional[str] = None
    """
    URL of a generated non-video file (e.g. 3D mesh).
    """
    last_frame_url: Optional[str] = None
    """
    URL of the last-frame image, when `return_last_frame` was requested.
    """
